package com.example.servercommon.message;

import java.text.MessageFormat;

public final class BackendMessageCatalog {

    private BackendMessageCatalog() {
    }

    // Error codes
    public static final String CODE_E400 = "E400";
    public static final String CODE_E4001 = "E4001";
    public static final String CODE_E4002 = "E4002";
    public static final String CODE_E4003 = "E4003";
    public static final String CODE_E401 = "E401";
    public static final String CODE_E4011 = "E4011";
    public static final String CODE_E4012 = "E4012";
    public static final String CODE_E4013 = "E4013";
    public static final String CODE_E4014 = "E4014";
    public static final String CODE_E4015 = "E4015";
    public static final String CODE_E403 = "E403";
    public static final String CODE_E4031 = "E4031";
    public static final String CODE_E4041 = "E4041";
    public static final String CODE_E409 = "E409";
    public static final String CODE_E500 = "E500";
    public static final String CODE_E5001 = "E5001";
    public static final String CODE_E5002 = "E5002";
    public static final String CODE_E5101 = "E5101";
    public static final String CODE_E5201 = "E5201";
    public static final String CODE_E6001 = "E6001";
    public static final String CODE_E1011 = "E1011";
    public static final String CODE_E1013 = "E1013";
    public static final String CODE_INVALID_USER = "INVALID_USER";
    public static final String CODE_TEMPLATE_PREVIEW_FAILED = "TEMPLATE_PREVIEW_FAILED";

    // Common argument labels
    public static final String ARG_TARGET = "target";
    public static final String ARG_IS_DELETED = "isdeleted";
    public static final String ARG_START_DATE = "start_date";
    public static final String ARG_MANUAL_ID = "manualId";
    public static final String ARG_NOTICE_ID_NOT_FOUND = "notice_id not found";
    public static final String ARG_USER_ID_NOT_FOUND = "user_id not found";
    public static final String ARG_MANUAL_NOT_FOUND = "manual not found";
    public static final String ARG_FILE = "file";
    public static final String ARG_FILE_COUNT = "file.count";
    public static final String ARG_FILE_NAME = "file.name";
    public static final String ARG_FILE_SIZE = "file.size";
    public static final String ARG_FILE_TYPE = "file.type";
    public static final String ARG_ROLE_ID = "role_id";
    public static final String ARG_REQUEST = "request";
    public static final String ARG_ROLE_NAME = "roleName";
    public static final String ARG_ROLE_ID_NOT_FOUND = "role_id not found";
    public static final String ARG_ROLE_NAME_ALREADY_EXISTS = "role_name already exists";
    public static final String ARG_ROLE_ALREADY_DELETED = "role already deleted";
    public static final String ARG_STATUS_LEVEL_ID = "statusLevelId";
    public static final String ARG_PERMISSION_ID = "permissionId";
    public static final String ARG_DUPLICATE_PERMISSION_ID = "duplicate permissionId";
    public static final String ARG_PERMISSION_MODULE_MISMATCH = "permission module mismatch";
    public static final String ARG_ROLE_PERMISSION_NOT_FOUND = "role_permission not found";
    public static final String ARG_USER_NOT_FOUND = "user not found";
    public static final String ARG_CURRENT_PASSWORD_INCORRECT = "current_password is incorrect";
    public static final String ARG_INVALID_TOKEN = "invalid token";
    public static final String ARG_TOKEN_ALREADY_USED = "token already used";
    public static final String ARG_TOKEN_EXPIRED = "token expired";
    public static final String ARG_INVALID_TOKEN_PURPOSE = "invalid token purpose";
    public static final String ARG_PASSWORD_ALREADY_SET = "password already set";
    public static final String ARG_PASSWORD_TOKEN_ALREADY_SENT = "password set/reset token already sent";

    // Generic API messages
    public static final String MSG_UNAUTHORIZED = "Unauthorized";
    public static final String MSG_ACCESS_DENIED = "Access Denied";
    public static final String MSG_INVALID_USER = "Invalid user";
    public static final String MSG_INVALID_TOKEN_FORMAT = "Invalid token format";
    public static final String MSG_TOKEN_PARSE_FAILED = "Token parse failed: {0}";
    public static final String MSG_INVALID_ID_TOKEN = "Invalid ID token: {0}";
    public static final String MSG_ACCOUNT_LOCKED = "Account is locked";
    public static final String MSG_ACCOUNT_DISABLED = "Account is disabled";
    public static final String MSG_ACCOUNT_EXPIRED = "Account is expired";
    public static final String MSG_CREDENTIALS_EXPIRED = "Credentials are expired";
    public static final String MSG_AUTHENTICATION_FAILED = "Authentication failed";
    public static final String MSG_REFRESH_TOKEN_COOKIE_MISSING = "REFRESH_TOKEN cookie is missing";
    public static final String MSG_UPLOAD_FAILED = "upload failed";
    public static final String MSG_LOGGED_OUT_SUCCESS = "Logged out successfully";
    public static final String MSG_LOGGED_OUT_BEST_EFFORT = "Logged out (best effort)";
    public static final String MSG_PASSWORD_UPDATED = "password updated";
    public static final String MSG_USER_DELETED = "user is deleted";
    public static final String MSG_USER_RESTORED = "user is restored";
    public static final String MSG_USER_UNLOCKED = "user is unlocked";
    public static final String MSG_PASSWORD_SET = "password has been set";
    public static final String MSG_RESET_PASSWORD_EMAIL_SENT = "reset password email sent";
    public static final String MSG_USER_ID_ALREADY_EXISTS = "user_id already exists";
    public static final String MSG_EMAIL_ALREADY_EXISTS = "email already exists";
    public static final String MSG_INVALID_ROLE_ID = "Invalid role id";
    public static final String MSG_USER_ALREADY_DELETED = "user already deleted";
    public static final String MSG_USER_ALREADY_ACTIVE = "user already active";
    public static final String MSG_CANNOT_UNLOCK_YOURSELF = "cannot unlock yourself";
    public static final String MSG_USER_PASSWORD_NOT_SET = "user password not set, cannot be unlocked";
    public static final String MSG_USER_IS_NOT_LOCKED = "user is not locked";
    public static final String MSG_SIGNATURE_VERIFICATION_FAILED = "Signature verification failed";
    public static final String MSG_SIGNATURE_OK = "Signature verified and data received";
    public static final String MSG_UNKNOWN_ERROR_PREFIX = "Unknown error (code: ";
    public static final String MSG_UNKNOWN_ERROR_JA = "不明なエラー";
    public static final String MSG_INTERNAL_ERROR_JA = "内部エラー";
    public static final String MSG_INVALID_FILE_NAME_SUFFIX = " (ファイル名が不正です)";
    public static final String MSG_IMPORT_SUCCESS = "インポート完了: {0}";
    public static final String MSG_IMPORT_SUCCESS_DETAIL = "取り込み成功: {0}件";
    public static final String MSG_VALIDATION_FAILED_DETAIL = "バリデーション失敗:{0}{1}";
    public static final String MSG_EXCEPTION_OCCURRED = "例外発生: {0}";
    public static final String MSG_PERMISSIONS_UPDATED = "Permissions updated successfully";
    public static final String MSG_TEMPLATE_CACHE_RELOADED = "テンプレートキャッシュを再読み込みしました";
    public static final String MSG_ROLE_DELETE_BLOCKED_BY_USERS = "{0} user(s) use this role, cannot delete it";
    public static final String MSG_AUTH_TOKEN_MISSING = "Authentication token is missing.";
    public static final String MSG_AUTH_TOKEN_INVALID = "Authentication token is invalid.";
    public static final String MSG_AUTH_TOKEN_EXPIRED = "Authentication token has expired.";
    public static final String EVENT_AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING";
    public static final String EVENT_AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID";
    public static final String EVENT_AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED";
    public static final String MSG_ERROR_PREFIX = "Error: {0}";
    public static final String MSG_JOB_COMPLETED_JA = "ジョブは正常に終了しました。";
    public static final String MSG_DUMMY_JOB_COMPLETED = "Dummy job completed successfully";
    public static final String MSG_JOB_EXECUTION_STARTED = "ジョブ [{0}] の実行を開始しました";
    public static final String MSG_DUMMY_JOB_EXECUTION_STARTED = "ダミージョブの実行を開始しました";

    // Log messages
    public static final String LOG_VALIDATION_ERROR = "Validation error: {}";
    public static final String LOG_BAD_CREDENTIALS_EXCEPTION = "BadCredentialsException handled: {}";
    public static final String LOG_ACCESS_DENIED = "Access denied: {}";
    public static final String LOG_CUSTOM_EXCEPTION = "CustomException caught: {}";
    public static final String LOG_ILLEGAL_ARGUMENT = "IllegalArgumentException: {}";
    public static final String LOG_INVALID_JOB_NAME = "InvalidJobNameException: {}";
    public static final String LOG_MALFORMED_JSON = "Malformed JSON request: {}";
    public static final String LOG_UNHANDLED_EXCEPTION = "Unhandled exception occurred";
    public static final String LOG_TEAMS_NOTIFY_FAILED = "Teams notification failed: {}";
    public static final String LOG_REPORT_GENERATION_ERROR = "Report generation failed: {}";
    public static final String LOG_STORAGE_ERROR = "Storage access error: {}";
    public static final String LOG_FILE_IMPORT_ERROR = "File import failed: {}";
    public static final String LOG_DATA_ACCESS_EXCEPTION = "DataAccessException caught: {}";
    public static final String LOG_SIGNATURE_VERIFICATION_FAILED = "Signature verification failed: {}";

    public static final String LOG_MANUAL_UPLOAD_FAILED = "Manual upload failed";
    public static final String LOG_MANUAL_DOWNLOAD_REQUESTED = "Manual download requested for docId: {}";
    public static final String LOG_SEARCH_FILE_PREFIX = "Searching for file with prefix: {}";
    public static final String LOG_FILE_NOT_FOUND_BY_PREFIX = "File not found for prefix: {}";
    public static final String LOG_FOUND_FILE_KEY = "Found file key: {}";
    public static final String LOG_FILE_NOT_FOUND = "File not found: {}";
    public static final String LOG_MANUAL_DOWNLOAD_FAILED = "Manual download failed: {}";

    public static final String LOG_NOTICE_UPLOAD_FAILED = "Notice upload failed";
    public static final String LOG_NOTICE_DOWNLOAD_REQUESTED = "Notice download requested for docId: {}";
    public static final String LOG_NOTICE_DOWNLOAD_FAILED = "Notice download failed: {}";

    public static final String LOG_FILE_UPLOAD_SUCCESS = "File upload succeeded: {}";
    public static final String LOG_FILE_UPLOAD_FAILED = "File upload failed";
    public static final String LOG_FILE_EXTENSION_NOT_CONFIGURED = "Allowed file extensions are not configured.";
    public static final String LOG_FILE_DOWNLOAD_FAILED = "File download failed: {}";
    public static final String LOG_FILE_DELETE_SUCCESS = "File delete succeeded: {}";
    public static final String LOG_FILE_DELETE_FAILED = "File delete failed: {}";

    public static final String LOG_REFRESH_ENDPOINT_CALLED = "/auth/refresh called";
    public static final String LOG_GBIZ_AUTH_URL_GENERATING = "Generating gbiz authorization URL...";
    public static final String LOG_GBIZ_AUTH_URL_BUILD_FAILED = "Failed to build authorization URI";
    public static final String LOG_EXTERNAL_TOKEN_RESPONSE = "Token response body: {}";
    public static final String LOG_EXTERNAL_USERINFO_RESPONSE = "UserInfo response body: {}";
    public static final String LOG_EXTERNAL_USERINFO_FETCH_FAILED = "Failed to fetch user info";
    public static final String LOG_REFRESH_TOKEN_SUCCESS = "Token refreshed successfully";
    public static final String LOG_REFRESH_TOKEN_FAILED = "Failed to refresh access token";
    public static final String LOG_GBIZ_IDTOKEN_VERIFIED = "ID token verified: sub={}, exp={}";
    public static final String LOG_GBIZ_IDTOKEN_VERIFY_FAILED = "ID token verification failed: {}";
    public static final String LOG_GBIZ_IDTOKEN_PROCESS_ERROR = "ID token processing error";
    public static final String LOG_GBIZ_PUBLIC_KEY_FETCHED = "Gbiz public key fetched (modulus bits = {})";
    public static final String LOG_LOGOUT_ERROR = "Logout error: {}";
    public static final String LOG_REVOKE_REFRESH_FAILED = "Failed to revoke refresh token on logout: {}";

    public static final String LOG_LOADING_USER_BY_USER_ID = "Loading user by userId: {}";
    public static final String LOG_USER_NOT_FOUND = "User not found: {}";
    public static final String LOG_NO_EXTENSION = "No file extension found in upload file name";
    public static final String LOG_TEMPLATE_JSON_PARSE_ERROR = "Template JSON parse error: {}";
    public static final String LOG_TEMPLATE_FIELD_PATH = "Template field path:";
    public static final String LOG_TEMPLATE_FIELD_ITEM = " - {}";
    public static final String LOG_GUEST_ROLE_DETECTED = "Guest role detected: {}";
    public static final String LOG_SAMPLE_JOB_STEP_EXECUTED = "Sample job step executed";
    public static final String LOG_SAMPLE_STEP_EXECUTED = "Step executed using StepBuilder directly";
    public static final String LOG_SYNC_RESPONSE = "Sync sample response: {}";
    public static final String LOG_SYNC_SEND_ERROR = "Sync sample send error: {}";
    public static final String LOG_SYNC_RECEIVED_DATA = "Received sync data: {}";
    public static final String LOG_BOOTSTRAP_HASH = "Bootstrap BCrypt hash for '{}': {}";
    public static final String LOG_ENV_RESOLVE_DEFAULT = "Failed to resolve property key={} as type={}. Using default value.";
    public static final String LOG_REPORT_URL_REGENERATE_FAILED = "Failed to regenerate report URL: jobName={}, error={}";
    public static final String LOG_INTERNAL_LOGIN_ATTEMPT = "Attempting internal login for userId: {}";
    public static final String LOG_FILE_UPLOAD_PROCESS_ERROR = "Error occurred during file upload processing";
    public static final String LOG_VALIDATION_RESULT_COUNT = "Validation result count: {}";
    public static final String LOG_VALIDATION_ROW_RESULT = "Row {}: valid={}, errors={}";

    public static final String LOG_S3_TEMP_FETCH_FAILED = "Failed to fetch temporary file from S3: {}";
    public static final String LOG_S3_GET_FILE_FAILED = "Failed to fetch file from S3: {}";
    public static final String LOG_S3_UPLOAD_FAILED = "Failed to upload file to S3: {}";
    public static final String LOG_S3_KEY_MISSING_FOR_MOVE = "S3 key is missing, move skipped: {}";
    public static final String LOG_S3_MOVE_SUCCESS = "S3 file moved: {} -> {}";
    public static final String LOG_S3_MOVE_FAILED = "Failed to move S3 file: {}";
    public static final String LOG_S3_PRESIGNED_URL_FAILED = "Failed to generate pre-signed URL for S3 object: {}";
    public static final String LOG_S3_DELETE_SUCCESS = "S3 file deleted: {}";
    public static final String LOG_S3_DELETE_FAILED = "Failed to delete S3 file: {}";
    public static final String LOG_S3_PREFIX_SEARCH_FAILED = "Failed to search S3 by prefix: {}";

    public static final String LOG_LOCAL_SAVE_FAILED = "Failed to save local file: {}";
    public static final String LOG_LOCAL_INPUT_LIST_FAILED = "Failed to list local input directory: {}";
    public static final String LOG_LOCAL_GET_FILE_FAILED = "Failed to fetch file from local storage: {}";
    public static final String LOG_LOCAL_MOVE_FAILED = "Failed to move local file: {}";
    public static final String LOG_LOCAL_INVALID_URL_FORMAT = "Invalid URL format: {}";
    public static final String LOG_LOCAL_DELETE_SUCCESS = "Local file deleted: {}";
    public static final String LOG_LOCAL_DELETE_FAILED = "Failed to delete local file: {}";
    public static final String LOG_LOCAL_PREFIX_SEARCH_FAILED = "Failed to search local files by prefix: {}";

    public static final String LOG_FILE_IMPORT_START = "File import started: templateId={}, filename={}";
    public static final String LOG_TEMPLATE_LOAD_FAILED = "Failed to load template: templateId={}";
    public static final String LOG_SHEET_LOADING = "Loading sheet: {}";
    public static final String LOG_FILE_IMPORT_COMPLETED = "File import completed: invalidCount={}";
    public static final String LOG_FILE_IMPORT_UNEXPECTED_ERROR = "Unexpected error while processing file";
    public static final String LOG_SKIP_ENTITY_SAVE_BY_VALIDATION = "Skipping entity save due to validation errors: {}";
    public static final String LOG_ENTITY_SAVE_SUCCESS = "Saved entities: count={}, entity={}";
    public static final String LOG_ENTITY_SAVE_FAILED = "Failed to save entity: {}";
    public static final String LOG_REPOSITORY_SAVE_FAILED = "Failed to persist entities via repository";

    public static final String LOG_CSV_READ_START = "Start reading CSV file: {}";
    public static final String LOG_EXCEL_READ_START = "Start reading Excel file (first sheet): {}";
    public static final String LOG_UNSUPPORTED_FILE_TYPE = "Unsupported file type: {}";
    public static final String LOG_FILE_READ_FAILED = "Failed to read file: {}";
    public static final String LOG_EXCEL_FIRST_SHEET_READ = "Excel first sheet read: {}";
    public static final String LOG_EXCEL_FIRST_SHEET_READ_FAILED = "Failed to read Excel first sheet";
    public static final String LOG_EXCEL_SHEET_NOT_FOUND = "Excel sheet not found: {}";
    public static final String LOG_EXCEL_SPECIFIED_SHEET_READ = "Excel specified sheet read: {}";
    public static final String LOG_EXCEL_SPECIFIED_SHEET_READ_FAILED = "Failed to read Excel sheet: {}";
    public static final String LOG_MANUAL_FILE_UPLOAD_FAILED = "Manual file upload failed: {}";
    public static final String LOG_MANUAL_UPLOAD_VALIDATION_FILE_NULL = "Manual upload validation: file is null";
    public static final String LOG_MANUAL_UPLOAD_VALIDATION_FILE_EMPTY = "Manual upload validation: file is empty. name={}, size={}";
    public static final String LOG_MANUAL_UPLOAD_VALIDATION_NAME_BLANK = "Manual upload validation: originalName is null or blank";
    public static final String LOG_NOTICE_FILE_UPLOAD_FAILED = "Notice file upload failed: {}";
    public static final String LOG_NOTICE_DIR_NOT_FOUND = "Notice directory does not exist: {}";
    public static final String LOG_NOTICE_DIR_SEARCH_FAILED = "Failed to search notice directory: {}";
    public static final String LOG_AUTH_PROPERTIES_SEPARATOR = "===========================================================================";
    public static final String LOG_AUTH_PROPERTIES_BEAN_ID = "AuthProperties Bean ID = {}";
    public static final String LOG_AUTH_PROPERTIES_CONTEXT = "AuthProperties Context = {}";
    public static final String LOG_AUTH_TYPE = "auth.type = {}";
    public static final String LOG_AUTH_GBIZ_URL = "gbiz.authUrl = {}";
    public static final String LOG_AUTH_INTERNAL_URL = "internal.authUrl = {}";
    public static final String LOG_TOKEN_REFRESH_REQUEST = "TokenRefreshFilter: {} {}";
    public static final String LOG_TOKEN_REFRESH_NO_TOKEN = "TokenRefreshFilter: no token found (cookie/header).";
    public static final String LOG_TOKEN_REFRESH_FOUND = "TokenRefreshFilter: token found (len={})";
    public static final String LOG_TOKEN_REFRESH_AUTHENTICATED = "TokenRefreshFilter: authenticated userId={}";
    public static final String LOG_TOKEN_REFRESH_EXPIRED = "TokenRefreshFilter: token expired";
    public static final String LOG_TOKEN_REFRESH_INVALID = "TokenRefreshFilter: token invalid";
    public static final String LOG_TOKEN_REFRESH_REVOKE_FAILED = "TokenRefreshFilter: failed to revoke refresh token for access jti={}";
    public static final String LOG_ENDPOINT_CONFIG_DB_HEADER = "=== Endpoint configuration loaded from DB ===";
    public static final String LOG_ENDPOINT_CONFIG_MEMORY_HEADER = "=== Loaded endpoint permissions (in-memory) ===";
    public static final String LOG_ENDPOINT_CONFIG_LOADED = "Loaded endpoint: {}";
    public static final String LOG_ENDPOINT_CONFIG_ALLOWED_ROLES = "  Allowed roles: {}";
    public static final String LOG_ENDPOINT_CONFIG_CUSTOM_PERMISSIONS = "  Custom permissions: {}";
    public static final String LOG_ENDPOINT_CONFIG_DEFAULT_LEVEL = "  Default required level: {}";
    public static final String LOG_ENDPOINT_CONFIG_DB_FOOTER = "=============================================";
    public static final String LOG_ENDPOINT_CONFIG_MEMORY_FOOTER = "==============================================";
    public static final String LOG_NOTIFY_SCAN_FOUND = "Notify scan found {} unnotified records";
    public static final String LOG_NOTIFY_SCAN_ERROR = "Notify scan error: queueId={}, error={}";
    public static final String LOG_NOTIFY_SCAN_FINISHED = "Notify scan finished. successCount={}, failureCount={}";
    public static final String LOG_NOTIFY_DELIVERED = "Notify delivered: id={}, type={}";
    public static final String LOG_NOTIFY_FAILED = "Notify failed: id={}, type={}, reason={}";
    public static final String LOG_NOTIFY_RETRY_WAIT = "Notify moved to RETRY_WAIT: id={}, type={}, retryCount={}, nextAttemptAt={}";
    public static final String LOG_NOTIFY_FINAL_FAILED = "Notify moved to FAILED: id={}, type={}, retryCount={}, reason={}";
    public static final String LOG_NOTIFY_UNKNOWN_EVENT_TYPE = "Notify unknown eventType detected: {}";
    public static final String LOG_NOTIFY_QUEUE_REGISTERED = "Notify queue registered: type={}, refId={}";
    public static final String LOG_SYNC_OUTBOX_REGISTERED = "Sync outbox registered: requestId={}, type={}, path={}";
    public static final String LOG_SYNC_OUTBOX_DUPLICATE = "Sync outbox duplicate requestId detected: requestId={}, status={}";
    public static final String LOG_SYNC_OUTBOX_SENT = "Sync outbox sent successfully: requestId={}, type={}";
    public static final String LOG_SYNC_OUTBOX_RETRY_WAIT = "Sync outbox moved to RETRY_WAIT: requestId={}, retryCount={}, nextRetryAt={}";
    public static final String LOG_SYNC_OUTBOX_FAILED = "Sync outbox moved to FAILED: requestId={}, retryCount={}, reason={}";
    public static final String LOG_SYNC_OUTBOX_DISPATCH_ERROR = "Sync outbox dispatch error: requestId={}, error={}";
    public static final String LOG_SYNC_OUTBOX_RETRY_SCAN = "Sync outbox retry scan: targets={}";
    public static final String LOG_JOB_RUN_START = "Job [{}] started";
    public static final String LOG_JOB_RUN_COMPLETED = "Job [{}] completed";
    public static final String LOG_JOB_RUN_FAILED = "Job [{}] failed: {}";
    public static final String LOG_DUMMY_JOB_STARTED = "Dummy job started";
    public static final String LOG_REPORT_POLLING_ERROR = "Error occurred during report polling batch: {}";
    public static final String LOG_ASYNC_JOB_CLEANUP_SCAN = "Async job cleanup scan: targets={}";
    public static final String LOG_ASYNC_JOB_EXPIRED = "Async job expired: jobName={}, artifactPath={}";
    public static final String LOG_ASYNC_JOB_CLEANUP_ERROR = "Async job cleanup error: jobName={}, error={}";
    public static final String LOG_FILE_IMPORT_RUNNER_INVALID_FILENAME = "Invalid file name";
    public static final String LOG_FILE_IMPORT_RUNNER_COMPLETED = "Import job completed: {}, status: {}";
    public static final String LOG_FILE_IMPORT_RUNNER_CLASS_NOT_FOUND = "Entity class not found: {}";
    public static final String LOG_FILE_IMPORT_RUNNER_FILE_ERROR = "File processing error: {}";
    public static final String LOG_API_RESPONSE_MESSAGE = "ApiResponse.message={}";
    public static final String LOG_REQUIRE_PERMISSION_SKIP = "RequirePermission SKIP {} {}";
    public static final String LOG_REQUIRE_PERMISSION_ACCESS_DENIED = "Access denied: {} {} for roleId={}, permissionId={}, status={}";
    public static final String LOG_REQUEST_PREHANDLE = "PreHandle - {} {}";
    public static final String LOG_SESSION_CHECK_SKIP_OPTIONS = "[SessionCheck] SKIP OPTIONS {}";
    public static final String LOG_DUMMY_JOB_REQUEST = "Dummy job request received";
    public static final String LOG_SYSTEM_SETTING_CACHE_HIT = "System setting cache hit: key={}";
    public static final String LOG_SYSTEM_SETTING_CACHE_MISS = "System setting cache miss: key={}";
    public static final String LOG_SYSTEM_SETTING_CACHE_EVICT = "System setting cache evicted: key={}";
    public static final String LOG_SYSTEM_SETTING_CACHE_EVICT_ALL = "System setting cache evicted: all keys";
    public static final String LOG_SYSTEM_SETTING_KEY_NOT_FOUND = "System setting key not found: key={}";
    public static final String LOG_SYSTEM_SETTING_ROW_NOT_FOUND = "System setting row not found: id={}";

    // Exception templates
    public static final String EX_FILE_SAVE_FAILED = "File save failed";
    public static final String EX_BATCH_START_FAILED = "Batch server job start failed: {0}";
    public static final String EX_TOKEN_REFRESH_FAILED = "Token refresh failed: {0}";
    public static final String EX_REFRESH_RESPONSE_INVALID = "Refresh token failed: invalid response";
    public static final String EX_GBIZ_PUBLIC_KEY_FETCH_FAILED = "Failed to fetch gbiz public key: {0}";
    public static final String EX_TEMPLATE_MAPPING_ERROR = "Template file mapping error.";
    public static final String EX_TEMPLATE_UNEXPECTED_ERROR = "Unexpected error while loading YAML template.";
    public static final String EX_TEMPLATE_FILE_NOT_FOUND = "Template file not found: {0}.yaml";
    public static final String EX_USER_NOT_FOUND_FOR_REFRESH_UID = "User not found for refresh token uid: {0}";
    public static final String EX_USER_NOT_FOUND = "User not found: {0}";
    public static final String EX_JWK_KEY_NOT_FOUND = "No key found in JWK set";
    public static final String EXCEL_GENERATION_FAILED = "Excel generation failed";
    public static final String PDF_GENERATION_FAILED = "PDF generation failed";
    public static final String EX_CONFIG_REQUIRED = "{0} is not configured";
    public static final String EX_FILE_PATH_EMPTY = "File path is empty";
    public static final String EX_FILE_FETCH_FAILED = "Failed to fetch file: {0}";
    public static final String EX_S3_UPLOAD_FAILED = "Failed to upload file to S3";
    public static final String EX_S3_PRESIGNED_URL_FAILED = "Failed to generate S3 pre-signed URL";
    public static final String EX_S3_DELETE_FAILED = "Failed to delete file from S3";
    public static final String EX_LOCAL_FILE_SAVE_FAILED = "Failed to save local file";
    public static final String EX_LOCAL_TEMPLATE_FETCH_FAILED = "Failed to fetch local template: {0}";
    public static final String EX_RESOURCE_NOT_FOUND = "Resource not found: {0}";
    public static final String EX_INVALID_URL_FORMAT = "Invalid URL format";
    public static final String EX_LOCAL_DELETE_FAILED = "Failed to delete local file";
    public static final String EX_TEMPLATE_LOAD_FAILED = "Failed to load template: {0}";
    public static final String EX_STREAM_READ_FAILED = "Failed to read input stream";
    public static final String EX_FILE_PROCESSING_FAILED = "Error occurred while processing file";
    public static final String EX_NOTIFY_EVENT_TYPE_REQUIRED = "eventType is required";
    public static final String EX_ENTITY_SAVE_FAILED = "Failed to save entity: {0}";
    public static final String EX_REPOSITORY_SAVE_FAILED = "Failed to save via repository";
    public static final String EX_INVALID_FILE_NAME = "File name is invalid";
    public static final String EX_UNSUPPORTED_FILE_TYPE = "Unsupported file type: {0}";
    public static final String EX_FILE_READ_FAILED = "Error occurred while reading file: {0}";
    public static final String EX_SHEET_READ_ONLY_EXCEL = "Sheet-read is supported only for Excel files: {0}";
    public static final String EX_SHEET_READ_FAILED = "Error occurred while reading sheet: {0}";
    public static final String EX_EXCEL_FIRST_SHEET_READ_FAILED = "Failed to read Excel first sheet";
    public static final String EX_EXCEL_SHEET_NOT_FOUND = "Sheet not found: {0}";
    public static final String EX_EXCEL_SPECIFIED_SHEET_READ_FAILED = "Failed to read Excel sheet: {0}";
    public static final String EX_EXCEL_SHEET_NO_DATA = "No data in sheet: {0}";
    public static final String EX_EXCEL_EMPTY_HEADER_COLUMN = "Header row contains empty column: {0}";
    public static final String EX_EXCEL_HEADER_EMPTY = "Header is empty: {0}";
    public static final String EX_EXCEL_NO_ROWS = "No data rows in sheet: {0}";
    public static final String EX_SET_PASSWORD_TEMPLATE_LOAD_FAILED = "Failed to load set password email template";
    public static final String EX_RESET_PASSWORD_TEMPLATE_LOAD_FAILED = "Failed to load reset password email template";
    public static final String EX_INVALID_AUTH_CONFIGURATION = "Invalid or missing auth configuration for type: {0}";
    public static final String EX_INVALID_TOKEN_CONFIGURATION = "Invalid or missing token configuration for type: {0}";
    public static final String EX_SESSION_REQUIRED = "session required";
    public static final String EX_REQUIRE_PERMISSION_MISSING = "Missing @RequirePermission on controller method";
    public static final String EX_JOB_NAME_REQUIRED = "jobName は必須です";
    public static final String EX_UNKNOWN_AUTH_TYPE = "Unknown auth type: {0}";
    public static final String EX_SECURITY_RSA_MODULUS_REQUIRED = "security.rsa-public-key.modulus-base64 is required";
    public static final String EX_SECURITY_RSA_EXPONENT_REQUIRED = "security.rsa-public-key.exponent-base64 is required";
    public static final String EX_GATEWAY_INVALID_JWT_TOKEN = "Invalid JWT token";
    public static final String EX_GATEWAY_MISSING_TOKEN_OR_SESSION = "Missing token or session";
    public static final String EX_GATEWAY_IP_DENIED = "Access denied from IP: {0}";
    public static final String EX_SYNC_JSON_CONVERSION_FAILED = "JSON変換に失敗しました";
    public static final String EX_HMAC_SIGNATURE_GENERATION_FAILED = "Failed to generate HMAC signature";
    public static final String EX_SYNC_MISSING_SIGNATURE_HEADER = "Missing {0} header";
    public static final String EX_SYNC_INVALID_SIGNATURE = "Invalid signature";
    public static final String EX_SYNC_CONTENT_CACHING_WRAPPER_REQUIRED = "Expected ContentCachingRequestWrapper. Make sure SyncSignatureCachingFilter is registered early in the filter chain.";
    public static final String EX_SIGNED_REST_TEMPLATE_UNAVAILABLE = "SignedRestTemplate is not available";
    public static final String EX_SIGNED_REST_TEMPLATE_SIGNATURE_INCOMPATIBLE =
            "SignedRestTemplate.post(...) signature is not compatible";
    public static final String EX_JOB_NOT_FOUND = "ジョブが見つかりません: {0}";
    public static final String EX_JOB_LAUNCH_FAILED = "ジョブ起動に失敗しました: {0}";
    public static final String EX_USERS_CSV_NOT_FOUND = "users.csv not found";
    public static final String EX_TEMPLATE_SCHEMA_REPOSITORY_REQUIRED = "TemplateSchema[{0}] に repository が指定されていません。";
    public static final String EX_REPOSITORY_RESOLVE_FAILED = "リポジトリの取得に失敗しました: {0}";
    public static final String EX_TEMPLATE_SCHEMA_COLUMNS_REQUIRED = "columns 定義が存在しません（v2テンプレートではこのメソッドは使用できません）";
    public static final String EX_TEMPLATE_SCHEMA_LOAD_FAILED = "テンプレートスキーマの読み込みに失敗しました: {0}";
    public static final String EX_TEMPLATE_SCHEMA_LOAD_FROM_PATH_FAILED = "テンプレートスキーマの読み込みに失敗しました（明示パス）: {0}";
    public static final String EX_CSV_READ_FAILED = "CSVファイルの読み取りに失敗しました";
    public static final String EX_MAIL_TEMPLATE_NOT_FOUND = "テンプレートが存在しません: {0}";
    public static final String EX_MAIL_TEMPLATE_LOCALE_NOT_FOUND = "指定されたロケールのテンプレートが存在しません";
    public static final String EX_MAIL_TEMPLATE_RENDER_FAILED = "テンプレートレンダリング失敗";
    public static final String EX_MAIL_TEMPLATE_SUBJECT_NOT_FOUND = "テンプレートの件名が取得できません";
    public static final String EX_ERROR_CODE_SERVICE_REQUIRED = "ErrorCodeServiceを必ず指定してください。";
    public static final String EX_UNSUPPORTED_DYNAMIC_REQUIRED_RULE = "Unsupported dynamicRequiredRule: {0}";
    public static final String EX_DYNAMIC_REQUIRED_RULE_INSTANTIATE_FAILED = "Failed to instantiate dynamicRequiredRule: {0}";
    public static final String EX_UNSUPPORTED_FILE_TYPE_JA = "未対応のファイル種別です: {0}";
    public static final String EX_CSV_HEADER_INVALID = "CSVヘッダーが不正です。期待値: {0}, 実際: {1}";
    public static final String EX_EXCEL_HEADER_ROW_MISSING = "Excelにヘッダー行が存在しません";
    public static final String EX_EXCEL_HEADER_INVALID = "Excelヘッダーが不正です。期待値: {0}, 実際: {1}";
    public static final String EX_COLUMN_COUNT_MISMATCH = "column count mismatch";
    public static final String EX_EXCEL_READ_PROCESS_FAILED = "Excelの読み取り中にエラーが発生しました";
    public static final String EX_FIELD_CONVERSION_FAILED = "フィールド変換失敗: {0} -> {1}";
    public static final String EX_ENTITY_CONVERSION_FAILED = "エンティティ変換に失敗しました: {0}";
    public static final String EX_ENTITY_INSTANCE_CREATE_FAILED = "エンティティのインスタンス生成に失敗しました: {0}";
    public static final String EX_UNSUPPORTED_TYPE = "未対応の型です: {0}";
    public static final String EX_INVALID_CODE_JA = "コードが不正 {0}";
    public static final String EX_INVALID_PROCESS_CATEGORY = "処理区分が不正 {0}";
    public static final String EX_INVALID_STATUS_TYPE_CODE = "Invalid StatusType code: {0}";
    public static final String EX_INVALID_STATUS_TYPE = "Invalid StatusType type: {0}";
    public static final String EX_INVALID_FILE_JOB_IMPORT_COLUMN = "Invalid FileJobImportCellType columNumber: {0}";
    public static final String EX_INVALID_FILE_JOB_IMPORT_POLICY = "Invalid FileJobImportCellType policy: {0}";
    public static final String EX_INVALID_CLOSURE_STATUS_CODE = "Invalid ClosureStatus code: {0}";
    public static final String EX_INVALID_CLOSURE_STATUS = "Invalid ClosureStatus status: {0}";
    public static final String EX_INVALID_BATCH_NAME = "バッチ名が不正: {0}";
    public static final String EX_INVALID_DISPLAY_NAME = "表示名が不正:{0}";
    public static final String EX_INVALID_PERMISSION_LEVEL_TYPE = "Invalid StatusType code: {0}";
    public static final String EX_INVALID_PERMISSION_LEVEL_CODE = "Invalid StatusType code: {0}";
    public static final String EX_INVALID_REGISTRATION_STATUS = "Invalid RegistrationStatus: {0}";
    public static final String EX_INVALID_JOB_TYPE_CODE = "Invalid JobType code: {0}";
    public static final String EX_INVALID_JOB_TYPE_LABEL = "Invalid JobType label: {0}";
    public static final String EX_INVALID_OUTPUT_FORMAT = "不正な出力形式: {0}";
    public static final String EX_BULK_REPORT_EXPORT_FAILED = "一括帳票出力に失敗しました: {0}";
    public static final String EX_REPORT_FETCHER_NOT_DEFINED = "帳票ID: {0} に対応するデータ取得処理が未定義です";
    public static final String EX_REPORT_FETCHER_NOT_DEFINED_SIMPLE = "reportId に対応するデータ取得処理が未定義です";
    public static final String EX_EXCEL_TEMPLATE_FETCH_FAILED = "Excelテンプレートの取得に失敗しました";
    public static final String EX_PDF_TEMPLATE_FETCH_FAILED = "PDFテンプレートの取得に失敗しました";
    public static final String EX_EXCEL_REPORT_UPLOAD_FAILED = "Excel帳票のアップロードに失敗しました";
    public static final String EX_PDF_REPORT_UPLOAD_FAILED = "PDF帳票のアップロードに失敗しました";
    public static final String EX_INVALID_EXPORT_TARGET = "Invalid exportTarget: {0}";
    public static final String EX_PRESIGNED_URL_GENERATION_FAILED = "Failed to generate presigned URL";
    public static final String EX_BASE64_CONVERSION_FAILED = "Base64 変換失敗";
    public static final String EX_REPORT_BINARY_CONVERSION_FAILED = "帳票バイナリ変換失敗";
    public static final String EX_REPORT_RECORD_NOT_FOUND = "帳票IDに対応するレコードが見つかりません: {0}";
    public static final String EX_PDF_RENDERER_INITIALIZATION_FAILED = "PDF renderer initialization failed";
    public static final String EX_EXCEL_TEMPLATE_OUTPUT_FAILED = "Excelテンプレート出力に失敗しました";
    public static final String EX_INVALID_DATE_FORMAT = "日付形式不正: {0}";
    public static final String EX_UNSUPPORTED_FILE_FORMAT = "未対応のファイル形式: {0}";
    public static final String EX_UNSUPPORTED_KEY_TYPE = "サポートされていないキータイプ: {0}";
    public static final String EX_UNSUPPORTED_TEMPLATE = "未対応のテンプレート: {0}";
    public static final String EX_SKIP_RULE_INSTANTIATE_FAILED = "Failed to instantiate SkipRule: {0}";
    public static final String EX_REPORT_NOT_FOUND = "帳票が見つかりません: {0}";
    public static final String EX_REPORT_LAYOUT_NOT_FOUND = "帳票レイアウトが存在しません: {0}";
    public static final String EX_ERROR_CODES_PROPERTIES_LOAD_FAILED = "Failed to load error codes from properties";
    public static final String EX_SYSTEM_SETTING_CONVERSION_FAILED = "System setting conversion failed: key={0}, value={1}, type={2}";
    public static final String EX_SYSTEM_SETTING_UNSUPPORTED_TYPE = "Unsupported system setting target type: {0}";

    public static final String LOG_GATEWAY_IP_ALLOWED = "[IP ALLOWED] {} from {}";
    public static final String LOG_GATEWAY_IP_BLOCKED = "[IP BLOCKED] {} from {}";
    public static final String LOG_GATEWAY_CORS_CONFIG_LOADED = "Gateway CORS config loaded: origins={}, methods={}, headers={}, exposedHeaders={}, allowCredentials={}, maxAge={}";
    public static final String LOG_GATEWAY_IP_CHECK = "IP whitelist check: method={}, path={}, origin={}, extractedIp={}, xffRaw={}, allowedIps={}";
    public static final String LOG_GATEWAY_IP_PASSED = "IP whitelist passed: method={}, path={}, origin={}, ip={}";
    public static final String LOG_GATEWAY_IP_DENIED_DETAIL = "IP whitelist denied: method={}, path={}, origin={}, ip={}, allowedIps={}";
    public static final String LOG_GATEWAY_JWT_BYPASS_OPTIONS = "JWT filter bypass (OPTIONS): method={}, path={}, origin={}, ip={}";
    public static final String LOG_GATEWAY_JWT_BYPASS_API = "JWT filter bypass (/api/**): method={}, path={}, origin={}, ip={}";
    public static final String LOG_GATEWAY_JWT_BYPASS_PUBLIC = "JWT filter bypass (public path): method={}, path={}, origin={}, ip={}";
    public static final String LOG_GATEWAY_JWT_INVALID_BEARER = "JWT filter rejected invalid bearer token: method={}, path={}, origin={}, ip={}";
    public static final String LOG_GATEWAY_JWT_ACCEPTED_BEARER = "JWT filter accepted bearer token: method={}, path={}, origin={}, ip={}";
    public static final String LOG_GATEWAY_JWT_ACCEPTED_SESSION = "JWT filter accepted JSESSIONID: method={}, path={}, origin={}, ip={}";
    public static final String LOG_GATEWAY_JWT_REJECTED_MISSING = "JWT filter rejected request (missing token/session): method={}, path={}, origin={}, ip={}";
    public static final String LOG_ERROR_CODE_SERVICE_TEST_PROFILE = "ErrorCodeService: using properties file for test profile.";
    public static final String LOG_ERROR_MESSAGE_ARGS_MISMATCH = "Error message [{}] (locale={}) requires {} args, but only {} provided. Template={}";
    public static final String LOG_ERROR_PLACEHOLDER_ANALYZE_FAILED = "Failed to analyze placeholders in error message for code [{}]: {}";
    public static final String LOG_SES_MAIL_SENT = "メール送信成功: to={}, subject={}";
    public static final String LOG_SES_MAIL_SEND_FAILED = "{}";
    public static final String LOG_USER_WRITER_VALIDATION_ERROR = "Validation error at row {}: {}";
    public static final String LOG_USER_WRITER_SAVED = "{} users saved to DB";
    public static final String LOG_USER_WRITER_NO_VALID_USERS = "有効なユーザーが見つかりませんでした。登録スキップ。";
    public static final String LOG_MOCK_EMAIL_SENT = "[MockEmailSender] To: {}, Subject: {}, Body: {}";
    public static final String LOG_BATCH_INVALID_FILENAME = "無効なファイル名: {}";
    public static final String LOG_BATCH_RESULT = "結果: {}";
    public static final String LOG_BATCH_FILE_PROCESS_EXCEPTION = "ファイル処理中に例外が発生しました";
    public static final String LOG_BATCH_STEP_START = "Step [{}] 開始";
    public static final String LOG_BATCH_STEP_END = "Step [{}] 終了 - ステータス: {}";
    public static final String LOG_BATCH_JOB_START = "Job [{}] 開始: {}";
    public static final String LOG_BATCH_JOB_END = "Job [{}] 終了: {} - ステータス: {}";
    public static final String LOG_BATCH_JOB_PREPARE = "Job [{}] 開始準備中...";
    public static final String LOG_BATCH_JOB_DONE = "Job [{}] 完了！ステータス: {}";
    public static final String LOG_BATCH_FILE_SCAN_START = "ファイル監視タスク開始";
    public static final String LOG_BATCH_FILE_ALREADY_PROCESSED = "処理済みスキップ: {}";
    public static final String LOG_BATCH_FILE_DETECTED = "新規ファイル検出: {}";
    public static final String LOG_BATCH_FILE_PROCESS_FAILED = "処理失敗: {}";
    public static final String LOG_BATCH_FILE_SCAN_END = "ファイル監視タスク終了";
    public static final String LOG_NOTIFY_QUEUE_CLEANUP = "通知キューのクリーンアップ: {} 件削除 (before {})";
    public static final String LOG_TEMPLATE_LOAD_FROM_CLASSPATH = "classpath からテンプレート読み込み: {}";
    public static final String LOG_TEMPLATE_LOAD_FROM_FILESYSTEM = "ファイルシステムからテンプレート読み込み: {}";
    public static final String LOG_CSV_RECORDS_COUNT = "読み込んだ行数: {}";
    public static final String LOG_CSV_RECORD_ROW = "Row: {}";
    public static final String LOG_MAIL_TEMPLATE_CACHE_RELOADED = "メールテンプレートキャッシュ更新完了: {}";
    public static final String LOG_MAIL_SEND_FAILED = "メール送信に失敗しました: {}";
    public static final String LOG_FIELD_CONVERSION_FAILED = "フィールド変換失敗: class={}, field={}, value={}";
    public static final String LOG_ENTITY_CREATION_FAILED = "エンティティ生成失敗: class={}";
    public static final String LOG_BASE64_ENCODING_FAILED = "Base64 エンコード中にエラー";
    public static final String LOG_BINARY_CONVERSION_FAILED = "バイナリ変換中にエラー";
    public static final String LOG_FIELD_ACCESS_FAILED = "フィールド取得失敗: entityClass={}, field={}, error={}";
    public static final String LOG_EXCEL_TEMPLATE_OUTPUT_FAILED = "Excelテンプレート出力中にエラー";
    public static final String LOG_BULK_EXPORT_INVALID_FORMAT = "無効な出力形式指定: {}";
    public static final String LOG_BULK_REPORT_EXPORT_FAILED = "一括帳票出力に失敗: {}";
    public static final String LOG_REPORT_DEFINITION_CACHE_CLEARED = "ReportDefinition cache cleared for reportId: {}";
    public static final String LOG_REPOSITORY_RESOLVE_PROCESSING = "リポジトリ取得処理: repositoryName = {}";
    public static final String LOG_REPOSITORY_RESOLVE_FAILED = "リポジトリ取得失敗: repositoryName = {}, schema = {}";
    public static final String LOG_SES_STATIC_CREDENTIALS = "SES: StaticCredentialsProvider を使用 (mail.access-key が設定されています)";
    public static final String LOG_SES_DEFAULT_CREDENTIALS = "SES: DefaultCredentialsProvider を使用 (EC2ロール/環境変数/プロファイルを自動探索)";
    public static final String LOG_CSV_IMPORT_TASKLET_START = "CsvUserImportTasklet execute() 開始";
    public static final String LOG_CSV_IMPORT_TASKLET_FILE_NOT_FOUND = "CSVファイルが見つかりません！";
    public static final String LOG_CSV_IMPORT_TASKLET_FILE_OPENED = "CSVファイルがオープンされました";
    public static final String LOG_CSV_IMPORT_TASKLET_SKIP_HEADER = "ヘッダー行スキップ: {}";
    public static final String LOG_CSV_IMPORT_TASKLET_ROW_READ = "読み込んだ行: {}";
    public static final String LOG_CSV_IMPORT_TASKLET_COLUMN_SHORTAGE = "カラム数が不足しています: {}";
    public static final String LOG_CSV_IMPORT_TASKLET_REQUIRED_EMPTY = "必須カラムが空です: {}";
    public static final String LOG_CSV_IMPORT_TASKLET_INVALID_ROLE = "無効なロール値: {}. 固定値 VIEWER を設定します。";
    public static final String LOG_CSV_IMPORT_TASKLET_USER_CREATED = "ユーザー作成成功: {}";
    public static final String LOG_CSV_IMPORT_TASKLET_USER_CREATE_ERROR = "ユーザー作成エラー: {} - {}";
    public static final String LOG_CSV_IMPORT_TASKLET_END = "CsvUserImportTasklet execute() 終了";

    public static final String MSG_SES_MAIL_SEND_FAILED_DETAIL = "メール送信失敗%n宛先: %s%n件名: %s%nエラー: %s";
    public static final String MSG_SES_MAIL_SEND_FAILED_PREFIX = "【🚨メール送信エラー】\n";

    // Teams notification templates
    public static final String TEAMS_CRITICAL_ERROR_TEMPLATE = "[Critical Error]%nMessage: %s%nException: %s%nDetail: %s";
    public static final String TEAMS_REPORT_ERROR_TEMPLATE = "[Report Error]%nCode: %s%nException: %s%nDetail: %s";
    public static final String TEAMS_STORAGE_ERROR_PREFIX = "[Storage Error] ";

    // Fallback
    public static final String MSG_UNKNOWN_ERROR = "Unknown error";
    public static final String JSON_AUTH_ERROR_TEMPLATE = "{\n"
            + "  \"message\": \"{0}\",\n"
            + "  \"eventType\": \"{1}\",\n"
            + "  \"authenticated\": false\n"
            + "}\n";

    public static String format(String template, Object... args) {
        return MessageFormat.format(template, args == null ? new Object[0] : args);
    }
}
