spring:
  config:
    activate:
      on-profile: prd

# ==============================
# Appserver
# ==============================
appserver:
  spring:
    datasource:
      url: jdbc:mysql://prd-db-host:3306/common
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: prod_user
      password: ${DB_PASSWORD_PROD}
    flyway:
      enabled: false
  jwt:
    secret: ${JWT_SECRET_PROD}
    expiration: 86400000
  teams:
    webhook:
      url: ${TEAMS_WEBHOOK_PROD}
  logging:
    level:
      root: INFO
    appender: NONE
    file:
      path: /var/logs/${spring.application.name}

# ==============================
# Batchserver
# ==============================
batchserver:
  spring:
    datasource:
      url: jdbc:mysql://prd-db-host:3306/common
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: prd_user
      password: ${DB_PASSWORD_PROD}
    batch:
      initialize-schema: always
    flyway:
      enabled: false
  storage:
    type: local
  teams:
    webhook:
      url: ${TEAMS_WEBHOOK_PROD}
  logging:
    level:
      root: INFO
    appender: NONE
    file:
      path: /var/logs/${spring.application.name}

# ==============================
# Gateway
# ==============================
gateway:
  spring:
    redis:
      host: redis-prd
      port: 6379
  jwt:
    secret: ${JWT_SECRET_PROD}
  teams:
    webhook:
      url: ${TEAMS_WEBHOOK_PROD}
