columns:
  - name: 品目CD
    field: itemCd
    required: true
    entity: "com.example.servercommon.entity.MasterItem"

  - name: 品目名
    field: itemName
    entity: "com.example.servercommon.entity.MasterItem"

  - name: 運用開始日
    field: startOfApplicationDate
    required: true
    entity: "com.example.servercommon.entity.MasterItem"

  - name: 取引先CD
    field: clientCd
    entity: "com.example.servercommon.entity.MasterItem"
