spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: jdbc:mysql://prd-db-host:3306/common?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: ${DB_PASSWORD_PROD}
    hikari:
      connection-init-sql: SET time_zone = '+00:00'

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
    show-sql: false

  jackson:
    time-zone: Asia/Tokyo

  flyway:
    enabled: true

  session:
    store-type: jdbc

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

security:
  rsa-public-key:
    modulus-base64: "ALlQ9XnH/0W0nUuOAz5kz5nkt8dHjGl5V9V2vblqJmQF3pOtKpyX6GZ+W9D3xIZw7dLrZUPPMp4x6BLsJwrImz8="
    exponent-base64: "AQAB"
  auth:
    mode: jwt   # jwt or session

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

storage:
  type: s3
  s3:
    endpoint: http://57.182.223.75:9080
    access-key: minio
    secret-key: minio1234
    bucket: reports
    input-dir: input
    archive-dir: archive
    error-dir: error

# aws:
#   region: ap-northeast-1

# mail:
#   access-key: XXXXX
#   secret-key: YYYYY
#   from: xx@crj.dev.jems-cloud.jp

jwt:
  secret: ${JWT_SECRET_PROD}
  expiration: 86400000

teams:
  webhook:
    url: ${TEAMS_WEBHOOK_PROD}

logging:
  level:
    root: INFO
  appender: NONE
  file:
    path: /var/logs/${spring.application.name}

report:
  cache:
    enabled: true  # ← falseにすればキャッシュ無効で毎回DB取得

file:
  validation-error:
    output-path: s3://path #ダミーs3 パス
