spring.flyway.enabled=false
spring.batch.job.enabled=false
logging.level.org.springframework.batch=DEBUG
logging.level.com.example.batchserver=DEBUG
logging.level.com.example.batchserver.tasklet=DEBUG
