# workers/api/wrangler.toml
name = 'kantosportsclub'
main = "src/index.ts"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "http://localhost:3000"

[[d1_databases]]
binding = "DB"
database_name = "kantosportsclub"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"
