#!/usr/bin/env python3
"""
sonarHtmlExport.py

Generate an HTML SonarQube report with:
- Quality Gate pass/fail
- Analysis overview metrics
- Quality gate conditions
- Open/unresolved issues
- File-level duplicated lines
"""

import argparse
import datetime as dt
import html
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import urljoin

import requests
from requests import Session
from requests.exceptions import RequestException

I18N_TEXT: Dict[str, Dict[str, str]] = {
    "en": {
        "report_title": "SonarQube Analysis Report",
        "report_subtitle": "Project quality snapshot from the latest SonarQube analysis.",
        "meta_project": "Project",
        "meta_branch": "Branch",
        "meta_server_health": "Server Health",
        "meta_generated_at": "Generated At",
        "section_overview": "Overview",
        "section_quality_gate": "Quality Gate Conditions",
        "section_issue_summary": "Issue Summary",
        "section_issues_by_severity": "Open/Unresolved Issues by Severity",
        "section_issues_by_type": "Open/Unresolved Issues by Type",
        "section_duplicates": "Duplicated Files",
        "summary_by_severity": "By Severity",
        "summary_by_type": "By Type",
        "col_metric": "Metric",
        "col_status": "Status",
        "col_actual": "Actual Value",
        "col_comparator": "Comparator",
        "col_threshold": "Error Threshold",
        "col_type": "Type",
        "col_severity": "Severity",
        "col_file": "File",
        "col_line": "Line",
        "col_message": "Message",
        "col_rule": "Rule",
        "col_dup_lines": "Duplicated Lines",
        "no_quality_conditions": "No quality gate conditions returned.",
        "no_issues_in_group": "No issues in this group.",
        "no_unresolved_issues": "No unresolved issues found.",
        "no_duplicates": "No duplicated files found.",
        "no_issues": "No issues",
        "showing_issues": "Showing {shown} of {total} issues (use --max-issues 0 to include all).",
        "dup_group_title": "Duplicate Files",
        "footer": "Generated by sonarHtmlExport.py",
        "na": "N/A",
        "status_ok": "OK",
        "status_error": "ERROR",
        "status_warn": "WARN",
        "status_unknown": "UNKNOWN",
        "qg_passed": "Passed",
        "qg_failed": "Failed",
        "qg_warning": "Warning",
        "qg_unknown": "Unknown",
        "card_quality_gate": "Quality Gate",
        "card_last_analysis": "Last Analysis",
        "card_version": "Version",
        "card_loc": "Lines of Code",
        "card_bugs": "Bugs",
        "card_security": "Security",
        "card_maintainability": "Maintainability",
        "card_security_hotspots": "Security Hotspots",
        "card_coverage": "Coverage",
        "card_duplications": "Duplications",
        "card_reliability_rating": "Reliability Rating",
        "card_security_rating": "Security Rating",
        "card_maintainability_rating": "Maintainability Rating",
        "msg_auth_failed": "Authentication failed: token is invalid for this SonarQube server.",
        "msg_report_generated": "Report generated: {path}",
        "msg_http_error": "HTTP/API error: {error}",
        "msg_unexpected_error": "Unexpected error: {error}",
    },
    "jp": {
        "report_title": "SonarQube 解析レポート",
        "report_subtitle": "最新の SonarQube 解析結果をもとにした品質サマリーです。",
        "meta_project": "プロジェクト",
        "meta_branch": "ブランチ",
        "meta_server_health": "サーバー状態",
        "meta_generated_at": "生成日時",
        "section_overview": "概要",
        "section_quality_gate": "品質ゲート条件",
        "section_issue_summary": "課題サマリー",
        "section_issues_by_severity": "未解決課題（重大度別）",
        "section_issues_by_type": "未解決課題（種別別）",
        "section_duplicates": "重複ファイル",
        "summary_by_severity": "重大度別",
        "summary_by_type": "種別別",
        "col_metric": "メトリクス",
        "col_status": "状態",
        "col_actual": "実測値",
        "col_comparator": "比較条件",
        "col_threshold": "しきい値",
        "col_type": "種別",
        "col_severity": "重大度",
        "col_file": "ファイル",
        "col_line": "行",
        "col_message": "メッセージ",
        "col_rule": "ルール",
        "col_dup_lines": "重複行数",
        "no_quality_conditions": "品質ゲート条件は返却されませんでした。",
        "no_issues_in_group": "このグループに課題はありません。",
        "no_unresolved_issues": "未解決課題はありません。",
        "no_duplicates": "重複ファイルはありません。",
        "no_issues": "課題なし",
        "showing_issues": "全{total}件中 {shown}件を表示しています（すべて表示するには --max-issues 0 を指定）。",
        "dup_group_title": "重複ファイル",
        "footer": "sonarHtmlExport.py により生成",
        "na": "N/A",
        "status_ok": "正常",
        "status_error": "エラー",
        "status_warn": "警告",
        "status_unknown": "不明",
        "qg_passed": "合格",
        "qg_failed": "失敗",
        "qg_warning": "警告",
        "qg_unknown": "不明",
        "card_quality_gate": "品質ゲート",
        "card_last_analysis": "最終解析",
        "card_version": "バージョン",
        "card_loc": "コード行数",
        "card_bugs": "バグ",
        "card_security": "セキュリティ",
        "card_maintainability": "保守性",
        "card_security_hotspots": "セキュリティホットスポット",
        "card_coverage": "カバレッジ",
        "card_duplications": "重複率",
        "card_reliability_rating": "信頼性評価",
        "card_security_rating": "セキュリティ評価",
        "card_maintainability_rating": "保守性評価",
        "msg_auth_failed": "認証に失敗しました: この SonarQube サーバーでトークンが無効です。",
        "msg_report_generated": "レポートを生成しました: {path}",
        "msg_http_error": "HTTP/API エラー: {error}",
        "msg_unexpected_error": "予期しないエラー: {error}",
    },
}

METRIC_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "bugs": "Bugs",
        "vulnerabilities": "Security",
        "new_vulnerabilities": "New Security",
        "code_smells": "Maintainability",
        "new_code_smells": "New Maintainability",
        "coverage": "Coverage",
        "new_coverage": "New Coverage",
        "duplicated_lines_density": "Duplications",
        "new_duplicated_lines_density": "New Duplications",
        "reliability_rating": "Reliability Rating",
        "new_reliability_rating": "New Reliability Rating",
        "security_rating": "Security Rating",
        "new_security_rating": "New Security Rating",
        "sqale_rating": "Maintainability Rating",
        "new_maintainability_rating": "New Maintainability Rating",
        "security_hotspots": "Security Hotspots",
        "new_security_hotspots": "New Security Hotspots",
    },
    "jp": {
        "bugs": "バグ",
        "vulnerabilities": "セキュリティ",
        "new_vulnerabilities": "新規セキュリティ",
        "code_smells": "保守性",
        "new_code_smells": "新規保守性",
        "coverage": "カバレッジ",
        "new_coverage": "新規カバレッジ",
        "duplicated_lines_density": "重複率",
        "new_duplicated_lines_density": "新規重複率",
        "reliability_rating": "信頼性評価",
        "new_reliability_rating": "新規信頼性評価",
        "security_rating": "セキュリティ評価",
        "new_security_rating": "新規セキュリティ評価",
        "sqale_rating": "保守性評価",
        "new_maintainability_rating": "新規保守性評価",
        "security_hotspots": "セキュリティホットスポット",
        "new_security_hotspots": "新規セキュリティホットスポット",
    },
}

SEVERITY_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "BLOCKER": "BLOCKER",
        "HIGH": "HIGH",
        "MEDIUM": "MEDIUM",
        "LOW": "LOW",
        "INFO": "INFO",
        "UNKNOWN": "UNKNOWN",
    },
    "jp": {
        "BLOCKER": "最重要",
        "HIGH": "高",
        "MEDIUM": "中",
        "LOW": "低",
        "INFO": "情報",
        "UNKNOWN": "不明",
    },
}

ISSUE_TYPE_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "BUG": "BUG",
        "SECURITY": "SECURITY",
        "MAINTAINABILITY": "MAINTAINABILITY",
        "UNKNOWN": "UNKNOWN",
    },
    "jp": {
        "BUG": "バグ",
        "SECURITY": "セキュリティ",
        "MAINTAINABILITY": "保守性",
        "UNKNOWN": "不明",
    },
}

ISSUE_STATUS_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "OPEN": "OPEN",
        "CONFIRMED": "CONFIRMED",
        "REOPENED": "REOPENED",
        "RESOLVED": "RESOLVED",
        "CLOSED": "CLOSED",
        "TO_REVIEW": "TO_REVIEW",
        "IN_REVIEW": "IN_REVIEW",
        "REVIEWED": "REVIEWED",
        "ACCEPTED": "ACCEPTED",
        "FALSE_POSITIVE": "FALSE_POSITIVE",
        "FIXED": "FIXED",
        "UNKNOWN": "UNKNOWN",
    },
    "jp": {
        "OPEN": "未対応",
        "CONFIRMED": "確認済み",
        "REOPENED": "再オープン",
        "RESOLVED": "解決済み",
        "CLOSED": "クローズ",
        "TO_REVIEW": "レビュー待ち",
        "IN_REVIEW": "レビュー中",
        "REVIEWED": "レビュー済み",
        "ACCEPTED": "受け入れ済み",
        "FALSE_POSITIVE": "誤検知",
        "FIXED": "修正済み",
        "UNKNOWN": "不明",
    },
}


def build_url(base_url: str, path: str) -> str:
    return urljoin(base_url.rstrip("/") + "/", path.lstrip("/"))


def api_get(
    session: Session,
    base_url: str,
    path: str,
    params: Optional[Dict[str, Any]] = None,
    timeout: int = 20,
    verify_ssl: bool = True,
) -> Optional[Dict[str, Any]]:
    url = build_url(base_url, path)
    response = session.get(url, params=params, timeout=timeout, verify=verify_ssl)

    if response.status_code == 404:
        return None

    response.raise_for_status()
    return response.json()


def with_branch(params: Dict[str, Any], branch: Optional[str]) -> Dict[str, Any]:
    if branch:
        params["branch"] = branch
    return params


def escape(value: Any) -> str:
    return html.escape("" if value is None else str(value))


def labels_for(use_jp: bool) -> Dict[str, str]:
    return I18N_TEXT["jp" if use_jp else "en"]


def txt(labels: Dict[str, str], key: str) -> str:
    return labels.get(key, key)


def format_percent(value: Any, labels: Dict[str, str]) -> str:
    if value is None:
        return txt(labels, "na")
    text = str(value).strip()
    if not text:
        return txt(labels, "na")
    if text.endswith("%"):
        return text
    return f"{text}%"


def rating_to_grade(value: Any) -> str:
    try:
        grade_map = {1: "A", 2: "B", 3: "C", 4: "D", 5: "E"}
        return grade_map.get(int(float(value)), "N/A")
    except Exception:
        return "N/A"


def rating_display(value: Any, labels: Dict[str, str]) -> str:
    grade = rating_to_grade(value)
    if grade == "N/A" or value is None:
        return txt(labels, "na")
    return f"{grade} ({value})"


def format_sonar_datetime(raw: Optional[str], labels: Dict[str, str]) -> str:
    if not raw:
        return txt(labels, "na")
    for fmt in ("%Y-%m-%dT%H:%M:%S%z", "%Y-%m-%dT%H:%M:%S.%f%z"):
        try:
            return dt.datetime.strptime(raw, fmt).strftime("%Y-%m-%d %H:%M:%S %Z")
        except ValueError:
            pass
    return raw


def quality_gate_label(raw_status: Optional[str], labels: Dict[str, str]) -> str:
    mapping = {
        "OK": txt(labels, "qg_passed"),
        "ERROR": txt(labels, "qg_failed"),
        "WARN": txt(labels, "qg_warning"),
    }
    return mapping.get(raw_status or "", txt(labels, "qg_unknown"))


def condition_status_label(raw_status: Optional[str], labels: Dict[str, str]) -> str:
    mapping = {
        "OK": txt(labels, "status_ok"),
        "ERROR": txt(labels, "status_error"),
        "WARN": txt(labels, "status_warn"),
    }
    return mapping.get(raw_status or "", txt(labels, "status_unknown"))


def quality_gate_css(raw_status: Optional[str]) -> str:
    mapping = {"OK": "qg-passed", "ERROR": "qg-failed", "WARN": "qg-warn"}
    return mapping.get(raw_status or "", "qg-unknown")


def normalize_issue_type(raw_type: Any) -> str:
    value = str(raw_type or "UNKNOWN").strip().upper()
    mapping = {
        "VULNERABILITY": "SECURITY",
        "CODE_SMELL": "MAINTAINABILITY",
    }
    return mapping.get(value, value)


def normalize_severity(raw_severity: Any) -> str:
    value = str(raw_severity or "UNKNOWN").strip().upper()
    mapping = {
        "CRITICAL": "HIGH",
        "MAJOR": "MEDIUM",
        "MINOR": "LOW",
    }
    return mapping.get(value, value)


def display_metric_key(metric_key: Any, use_jp: bool) -> str:
    value = str(metric_key or "N/A").strip()
    return METRIC_LABELS["jp" if use_jp else "en"].get(value, value)


def localize_issue_type(value: Any, use_jp: bool) -> str:
    key = normalize_issue_type(value)
    return ISSUE_TYPE_LABELS["jp" if use_jp else "en"].get(key, key)


def localize_severity(value: Any, use_jp: bool) -> str:
    key = normalize_severity(value)
    return SEVERITY_LABELS["jp" if use_jp else "en"].get(key, key)


def localize_issue_status(value: Any, use_jp: bool) -> str:
    key = str(value or "UNKNOWN").strip().upper()
    return ISSUE_STATUS_LABELS["jp" if use_jp else "en"].get(key, key)


def normalized_issue_severity_for_sort(raw_severity: Any) -> str:
    return normalize_severity(raw_severity)


def issue_sort_key(issue: Dict[str, Any]) -> Any:
    severity_order = {
        "BLOCKER": 0,
        "HIGH": 1,
        "MEDIUM": 2,
        "LOW": 3,
        "INFO": 4,
        "UNKNOWN": 5,
    }
    severity = normalized_issue_severity_for_sort(issue.get("severity", "UNKNOWN"))
    issue_type = normalize_issue_type(issue.get("type", "UNKNOWN"))
    component = str(issue.get("component", ""))
    line = issue.get("line", 0)
    try:
        line_number = int(line)
    except Exception:
        line_number = 0
    return (
        severity_order.get(severity, 99),
        issue_type,
        component,
        line_number,
        str(issue.get("message", "")),
    )


def build_issue_group_table_rows(
    items: List[Dict[str, Any]],
    labels: Dict[str, str],
    use_jp: bool,
) -> str:
    rows: List[str] = []
    for issue in sorted(items, key=issue_sort_key):
        component = str(issue.get("component", ""))
        file_path = component.split(":", 1)[1] if ":" in component else component
        issue_type_raw = normalize_issue_type(issue.get("type", "UNKNOWN"))
        severity_raw = normalize_severity(issue.get("severity", "UNKNOWN"))
        severity_css = f"sev-{severity_raw.lower()}"
        status_raw = issue.get("status", issue.get("issueStatus", "UNKNOWN"))
        line_value = issue.get("line", txt(labels, "na"))
        if line_value in (None, ""):
            line_value = txt(labels, "na")

        rows.append(
            f"""
            <tr>
              <td>{escape(localize_issue_type(issue_type_raw, use_jp))}</td>
              <td class="{severity_css}">{escape(localize_severity(severity_raw, use_jp))}</td>
              <td>{escape(file_path)}</td>
              <td>{escape(line_value)}</td>
              <td>{escape(issue.get("message", ""))}</td>
              <td>{escape(localize_issue_status(status_raw, use_jp))}</td>
              <td>{escape(issue.get("rule", txt(labels, "na")))}</td>
            </tr>
            """
        )

    if not rows:
        return (
            f'<tr><td colspan="7" class="muted">'
            f'{escape(txt(labels, "no_issues_in_group"))}</td></tr>'
        )
    return "".join(rows)


def build_collapsible_issue_groups(
    issues: List[Dict[str, Any]],
    group_by: str,
    labels: Dict[str, str],
    use_jp: bool,
) -> str:
    grouped: Dict[str, List[Dict[str, Any]]] = {}
    if group_by == "severity":
        for issue in issues:
            key = normalize_severity(issue.get("severity", "UNKNOWN"))
            grouped.setdefault(key, []).append(issue)
        ordered_keys = ["BLOCKER", "HIGH", "MEDIUM", "LOW", "INFO", "UNKNOWN"]
    else:
        for issue in issues:
            key = normalize_issue_type(issue.get("type", "UNKNOWN"))
            grouped.setdefault(key, []).append(issue)
        ordered_keys = ["BUG", "SECURITY", "MAINTAINABILITY", "UNKNOWN"]

    html_chunks: List[str] = []
    for key in ordered_keys:
        if key not in grouped:
            continue
        count = len(grouped[key])
        detail_id = f"{group_by}-{key.lower()}"
        table_rows = build_issue_group_table_rows(grouped[key], labels, use_jp)
        group_label = (
            localize_severity(key, use_jp)
            if group_by == "severity"
            else localize_issue_type(key, use_jp)
        )

        html_chunks.append(
            f"""
            <details class="issue-group" id="{escape(detail_id)}">
              <summary>
                <span>{escape(group_label)}</span>
                <span class="summary-count">{count}</span>
              </summary>
              <div class="group-table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>{escape(txt(labels, "col_type"))}</th>
                      <th>{escape(txt(labels, "col_severity"))}</th>
                      <th>{escape(txt(labels, "col_file"))}</th>
                      <th>{escape(txt(labels, "col_line"))}</th>
                      <th>{escape(txt(labels, "col_message"))}</th>
                      <th>{escape(txt(labels, "col_status"))}</th>
                      <th>{escape(txt(labels, "col_rule"))}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {table_rows}
                  </tbody>
                </table>
              </div>
            </details>
            """
        )

    extra_groups = sorted([k for k in grouped.keys() if k not in ordered_keys])
    for key in extra_groups:
        count = len(grouped[key])
        detail_id = f"{group_by}-{key.lower()}"
        table_rows = build_issue_group_table_rows(grouped[key], labels, use_jp)
        group_label = (
            localize_severity(key, use_jp)
            if group_by == "severity"
            else localize_issue_type(key, use_jp)
        )

        html_chunks.append(
            f"""
            <details class="issue-group" id="{escape(detail_id)}">
              <summary>
                <span>{escape(group_label)}</span>
                <span class="summary-count">{count}</span>
              </summary>
              <div class="group-table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>{escape(txt(labels, "col_type"))}</th>
                      <th>{escape(txt(labels, "col_severity"))}</th>
                      <th>{escape(txt(labels, "col_file"))}</th>
                      <th>{escape(txt(labels, "col_line"))}</th>
                      <th>{escape(txt(labels, "col_message"))}</th>
                      <th>{escape(txt(labels, "col_status"))}</th>
                      <th>{escape(txt(labels, "col_rule"))}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {table_rows}
                  </tbody>
                </table>
              </div>
            </details>
            """
        )

    if not html_chunks:
        return f'<p class="muted">{escape(txt(labels, "no_unresolved_issues"))}</p>'
    return "".join(html_chunks)


def get_measures(
    session: Session,
    base_url: str,
    project_key: str,
    branch: Optional[str],
    timeout: int,
    verify_ssl: bool,
) -> Dict[str, str]:
    metric_keys = ",".join(
        [
            "alert_status",
            "ncloc",
            "bugs",
            "vulnerabilities",
            "code_smells",
            "security_hotspots",
            "coverage",
            "duplicated_lines_density",
            "reliability_rating",
            "security_rating",
            "sqale_rating",
        ]
    )
    data = api_get(
        session,
        base_url,
        "/api/measures/component",
        with_branch({"component": project_key, "metricKeys": metric_keys}, branch),
        timeout,
        verify_ssl,
    )
    measures: Dict[str, str] = {}
    for measure in (data or {}).get("component", {}).get("measures", []):
        metric = measure.get("metric")
        value = measure.get("value")
        if metric is not None and value is not None:
            measures[str(metric)] = str(value)
    return measures


def get_quality_gate(
    session: Session,
    base_url: str,
    project_key: str,
    branch: Optional[str],
    timeout: int,
    verify_ssl: bool,
) -> Dict[str, Any]:
    data = api_get(
        session,
        base_url,
        "/api/qualitygates/project_status",
        with_branch({"projectKey": project_key}, branch),
        timeout,
        verify_ssl,
    )
    return data or {}


def get_latest_analysis(
    session: Session,
    base_url: str,
    project_key: str,
    branch: Optional[str],
    timeout: int,
    verify_ssl: bool,
    labels: Dict[str, str],
) -> Dict[str, str]:
    data = api_get(
        session,
        base_url,
        "/api/project_analyses/search",
        with_branch({"project": project_key, "ps": 1}, branch),
        timeout,
        verify_ssl,
    )
    latest = {"date": txt(labels, "na"), "version": txt(labels, "na")}
    analyses = (data or {}).get("analyses", [])
    if analyses:
        first = analyses[0]
        latest["date"] = format_sonar_datetime(first.get("date"), labels)
        for event in first.get("events", []):
            if event.get("category") == "VERSION":
                latest["version"] = event.get("name", txt(labels, "na"))
                break
    return latest


def get_main_branch_name(
    session: Session,
    base_url: str,
    project_key: str,
    timeout: int,
    verify_ssl: bool,
) -> str:
    data = api_get(
        session,
        base_url,
        "/api/project_branches/list",
        {"project": project_key},
        timeout,
        verify_ssl,
    )
    for branch_data in (data or {}).get("branches", []):
        if branch_data.get("isMain"):
            return branch_data.get("name", "main")
    return "main"


def get_all_unresolved_issues(
    session: Session,
    base_url: str,
    project_key: str,
    branch: Optional[str],
    timeout: int,
    verify_ssl: bool,
) -> List[Dict[str, Any]]:
    issues: List[Dict[str, Any]] = []
    page = 1
    page_size = 500

    while True:
        params = with_branch(
            {
                "componentKeys": project_key,
                "resolved": "false",
                "p": page,
                "ps": page_size,
            },
            branch,
        )
        data = api_get(session, base_url, "/api/issues/search", params, timeout, verify_ssl)
        if not data:
            break

        current = data.get("issues", [])
        issues.extend(current)

        paging = data.get("paging", {})
        total = paging.get("total", data.get("total", len(issues)))
        current_size = paging.get("pageSize", page_size)

        if not current or (page * int(current_size)) >= int(total):
            break

        page += 1

    return issues


def get_duplicated_files(
    session: Session,
    base_url: str,
    project_key: str,
    branch: Optional[str],
    timeout: int,
    verify_ssl: bool,
) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []
    page = 1
    page_size = 500

    while True:
        params = with_branch(
            {
                "component": project_key,
                "metricKeys": "duplicated_lines",
                "qualifiers": "FIL",
                "p": page,
                "ps": page_size,
            },
            branch,
        )
        data = api_get(
            session,
            base_url,
            "/api/measures/component_tree",
            params,
            timeout,
            verify_ssl,
        )
        if not data:
            break

        components = data.get("components", [])
        for component in components:
            measures = component.get("measures", [])
            if not measures:
                continue
            raw = measures[0].get("value", "0")
            try:
                if int(float(raw)) > 0:
                    results.append(
                        {
                            "path": component.get("path", component.get("name", "N/A")),
                            "duplicated_lines": raw,
                        }
                    )
            except ValueError:
                continue

        paging = data.get("paging", {})
        total = paging.get("total")
        current_size = paging.get("pageSize", page_size)

        if not components:
            break
        if total is not None and (page * int(current_size)) >= int(total):
            break
        if total is None and len(components) < page_size:
            break

        page += 1

    return results


def duplicated_lines_sort_key(item: Dict[str, Any]) -> int:
    try:
        return int(float(item.get("duplicated_lines", 0)))
    except (TypeError, ValueError):
        return 0


def build_html(
    project_key: str,
    branch_name: str,
    quality_gate_raw: Optional[str],
    quality_gate_data: Dict[str, Any],
    measures: Dict[str, str],
    latest_analysis: Dict[str, str],
    issues: List[Dict[str, Any]],
    duplicated_files: List[Dict[str, Any]],
    server_health: str,
    generated_at: str,
    max_issues: int,
    use_jp: bool,
) -> str:
    labels = labels_for(use_jp)
    language = "ja" if use_jp else "en"

    qg_label = quality_gate_label(quality_gate_raw, labels)
    qg_class = quality_gate_css(quality_gate_raw)

    severity_counts = Counter(normalize_severity(issue.get("severity", "UNKNOWN")) for issue in issues)
    type_counts = Counter(normalize_issue_type(issue.get("type", "UNKNOWN")) for issue in issues)

    displayed_issues = issues if max_issues <= 0 else issues[:max_issues]
    truncated = len(displayed_issues) < len(issues)

    conditions = quality_gate_data.get("projectStatus", {}).get("conditions", [])
    condition_rows: List[str] = []
    for condition in conditions:
        status_raw = condition.get("status", "N/A")
        status_display = condition_status_label(status_raw, labels)
        status_class = "cond-ok" if status_raw == "OK" else ("cond-err" if status_raw == "ERROR" else "cond-warn")
        condition_rows.append(
            f"""
            <tr>
              <td>{escape(display_metric_key(condition.get("metricKey", "N/A"), use_jp))}</td>
              <td class="{status_class}">{escape(status_display)}</td>
              <td>{escape(condition.get("actualValue", txt(labels, "na")))}</td>
              <td>{escape(condition.get("comparator", txt(labels, "na")))}</td>
              <td>{escape(condition.get("errorThreshold", txt(labels, "na")))}</td>
            </tr>
            """
        )
    if not condition_rows:
        condition_rows.append(
            f'<tr><td colspan="5" class="muted">{escape(txt(labels, "no_quality_conditions"))}</td></tr>'
        )

    grouped_by_severity_html = build_collapsible_issue_groups(
        displayed_issues,
        group_by="severity",
        labels=labels,
        use_jp=use_jp,
    )
    grouped_by_type_html = build_collapsible_issue_groups(
        displayed_issues,
        group_by="type",
        labels=labels,
        use_jp=use_jp,
    )

    duplicate_file_count = len(duplicated_files)
    duplicate_rows: List[str] = []
    for duplicate in sorted(duplicated_files, key=duplicated_lines_sort_key, reverse=True):
        duplicate_rows.append(
            f"""
            <tr>
              <td>{escape(duplicate.get("path", txt(labels, "na")))}</td>
              <td>{escape(duplicate.get("duplicated_lines", txt(labels, "na")))}</td>
            </tr>
            """
        )
    if not duplicate_rows:
        duplicate_rows.append(
            f'<tr><td colspan="2" class="muted">{escape(txt(labels, "no_duplicates"))}</td></tr>'
        )

    cards = [
        (
            txt(labels, "card_quality_gate"),
            f'<span class="qg {qg_class}">{escape(qg_label)}</span>',
        ),
        (txt(labels, "card_last_analysis"), escape(latest_analysis.get("date", txt(labels, "na")))),
        (txt(labels, "card_version"), escape(latest_analysis.get("version", txt(labels, "na")))),
        (txt(labels, "card_loc"), escape(measures.get("ncloc", txt(labels, "na")))),
        (txt(labels, "card_bugs"), escape(measures.get("bugs", "0"))),
        (txt(labels, "card_security"), escape(measures.get("vulnerabilities", "0"))),
        (txt(labels, "card_maintainability"), escape(measures.get("code_smells", "0"))),
        (txt(labels, "card_security_hotspots"), escape(measures.get("security_hotspots", "0"))),
        (txt(labels, "card_coverage"), escape(format_percent(measures.get("coverage"), labels))),
        (
            txt(labels, "card_duplications"),
            escape(format_percent(measures.get("duplicated_lines_density"), labels)),
        ),
        (
            txt(labels, "card_reliability_rating"),
            escape(rating_display(measures.get("reliability_rating"), labels)),
        ),
        (
            txt(labels, "card_security_rating"),
            escape(rating_display(measures.get("security_rating"), labels)),
        ),
        (
            txt(labels, "card_maintainability_rating"),
            escape(rating_display(measures.get("sqale_rating"), labels)),
        ),
    ]
    cards_html = "".join(
        f"""
        <div class="stat-card">
          <div class="stat-label">{escape(label)}</div>
          <div class="stat-value">{value}</div>
        </div>
        """
        for label, value in cards
    )

    severity_order = ["BLOCKER", "HIGH", "MEDIUM", "LOW", "INFO", "UNKNOWN"]
    ordered_severity_keys = severity_order + sorted(
        [key for key in severity_counts.keys() if key not in severity_order]
    )
    severity_summary = "".join(
        f'<span class="summary-chip sev-chip-{key.lower()}">{escape(localize_severity(key, use_jp))}: '
        f'{escape(severity_counts[key])}</span>'
        for key in ordered_severity_keys
        if key in severity_counts
    ) or f'<span class="summary-chip">{escape(txt(labels, "no_issues"))}</span>'

    type_order = ["BUG", "SECURITY", "MAINTAINABILITY", "UNKNOWN"]
    ordered_type_keys = type_order + sorted([key for key in type_counts.keys() if key not in type_order])
    type_summary = "".join(
        f'<span class="summary-chip">{escape(localize_issue_type(key, use_jp))}: '
        f'{escape(type_counts[key])}</span>'
        for key in ordered_type_keys
        if key in type_counts
    ) or f'<span class="summary-chip">{escape(txt(labels, "no_issues"))}</span>'

    truncation_note = (
        f'<p class="muted">{escape(txt(labels, "showing_issues").format(shown=len(displayed_issues), total=len(issues)))}</p>'
        if truncated
        else ""
    )

    return f"""<!doctype html>
<html lang="{language}">
<head>
  <meta charset="utf-8" />
  <title>{escape(txt(labels, "report_title"))} - {escape(project_key)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    :root {{
      --bg: #f3f5f8;
      --surface: #fff;
      --surface-alt: #f8fafc;
      --text: #1f2937;
      --muted: #6b7280;
      --border: #e2e8f0;
      --ok: #0f766e;
      --err: #b91c1c;
      --warn: #b45309;
      --chip: #eef2f7;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: "Segoe UI", "Noto Sans JP", sans-serif;
      line-height: 1.45;
    }}
    .page {{ max-width: 1280px; margin: 0 auto; padding: 20px 14px 24px; }}
    .hero, .section {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 12px;
      margin-bottom: 12px;
      overflow: hidden;
    }}
    .hero {{ padding: 16px; }}
    .hero h1 {{ margin: 0; font-size: 28px; }}
    .hero p {{ margin: 8px 0 0; color: var(--muted); font-size: 14px; }}
    .hero-meta {{
      margin-top: 14px;
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 10px;
    }}
    .meta-item {{
      border: 1px solid var(--border);
      background: var(--surface-alt);
      border-radius: 10px;
      padding: 10px 12px;
    }}
    .meta-label {{
      display: block;
      color: var(--muted);
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      margin-bottom: 3px;
    }}
    .meta-value {{ font-size: 15px; font-weight: 600; word-break: break-word; }}
    .section-header {{
      padding: 12px 16px;
      border-bottom: 1px solid var(--border);
      background: var(--surface-alt);
    }}
    .section-header h2 {{ margin: 0; font-size: 18px; }}
    .section-content {{ padding: 14px 16px 16px; }}
    .stats-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 10px;
    }}
    .stat-card {{
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 12px;
      min-height: 80px;
    }}
    .stat-label {{
      color: var(--muted);
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      margin-bottom: 7px;
    }}
    .stat-value {{ font-size: 22px; font-weight: 700; word-break: break-word; }}
    .qg {{
      display: inline-block;
      border-radius: 999px;
      padding: 4px 10px;
      font-size: 13px;
      font-weight: 700;
      border: 1px solid transparent;
    }}
    .qg-passed {{ color: var(--ok); background: #ecfdf5; border-color: #a7f3d0; }}
    .qg-failed {{ color: var(--err); background: #fef2f2; border-color: #fecaca; }}
    .qg-warn {{ color: var(--warn); background: #fff7ed; border-color: #fed7aa; }}
    .qg-unknown {{ color: #475569; background: #f1f5f9; border-color: #cbd5e1; }}
    .summary-row {{ display: flex; align-items: flex-start; gap: 12px; margin-bottom: 10px; }}
    .summary-row:last-child {{ margin-bottom: 0; }}
    .summary-title {{
      min-width: 150px;
      color: var(--muted);
      font-size: 13px;
      font-weight: 700;
      padding-top: 5px;
    }}
    .summary-chips {{ display: flex; flex-wrap: wrap; gap: 8px; }}
    .summary-chip {{
      display: inline-flex;
      align-items: center;
      padding: 4px 10px;
      border-radius: 999px;
      font-size: 12px;
      font-weight: 600;
      background: var(--chip);
      color: #334155;
      border: 1px solid #d8e0ea;
    }}
    .sev-chip-blocker, .sev-chip-high {{ background: #fef2f2; color: #991b1b; border-color: #fecaca; }}
    .sev-chip-medium {{ background: #fff7ed; color: #9a3412; border-color: #fed7aa; }}
    .sev-chip-low {{ background: #eff6ff; color: #1d4ed8; border-color: #bfdbfe; }}
    .sev-chip-info {{ background: #f8fafc; color: #475569; border-color: #cbd5e1; }}
    .table-wrap, .group-table-wrapper {{ overflow-x: auto; }}
    table {{
      width: 100%;
      min-width: 720px;
      border-collapse: collapse;
      font-size: 13px;
    }}
    th, td {{
      border-bottom: 1px solid var(--border);
      text-align: left;
      padding: 9px 10px;
      vertical-align: top;
    }}
    th {{
      background: #f8fafc;
      color: #334155;
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      font-weight: 700;
    }}
    tbody tr:nth-child(even) {{ background: #fcfdff; }}
    .muted {{ color: var(--muted); }}
    .cond-ok {{ color: var(--ok); font-weight: 700; }}
    .cond-err {{ color: var(--err); font-weight: 700; }}
    .cond-warn {{ color: var(--warn); font-weight: 700; }}
    .sev-blocker, .sev-high {{ color: var(--err); font-weight: 700; }}
    .sev-medium {{ color: var(--warn); font-weight: 700; }}
    .sev-low {{ color: #1d4ed8; font-weight: 700; }}
    .sev-info {{ color: #475569; font-weight: 700; }}
    .issue-group {{
      border: 1px solid var(--border);
      border-radius: 10px;
      margin-bottom: 10px;
      overflow: hidden;
    }}
    .issue-group:last-child {{ margin-bottom: 0; }}
    .issue-group summary {{
      cursor: pointer;
      padding: 10px 12px;
      background: #f8fafc;
      font-weight: 700;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 10px;
      list-style: none;
    }}
    .issue-group summary::-webkit-details-marker {{ display: none; }}
    .summary-count {{
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-width: 28px;
      height: 24px;
      border-radius: 999px;
      font-size: 12px;
      font-weight: 700;
      background: #e5edff;
      color: #1e40af;
      border: 1px solid #bfdbfe;
      padding: 0 8px;
      flex-shrink: 0;
    }}
    .issue-group[open] > summary {{ border-bottom: 1px solid var(--border); }}
    .group-table-wrapper {{ padding: 0 12px 12px; }}
    .footer {{ text-align: center; color: var(--muted); font-size: 12px; padding-top: 2px; }}
    @media (max-width: 900px) {{
      .hero h1 {{ font-size: 22px; }}
      .summary-row {{ flex-direction: column; gap: 8px; }}
      .summary-title {{ min-width: 0; padding-top: 0; }}
    }}
  </style>
</head>
<body>
  <main class="page">
    <header class="hero">
      <h1>{escape(txt(labels, "report_title"))}</h1>
      <p>{escape(txt(labels, "report_subtitle"))}</p>
      <div class="hero-meta">
        <div class="meta-item"><span class="meta-label">{escape(txt(labels, "meta_project"))}</span><span class="meta-value">{escape(project_key)}</span></div>
        <div class="meta-item"><span class="meta-label">{escape(txt(labels, "meta_branch"))}</span><span class="meta-value">{escape(branch_name)}</span></div>
        <div class="meta-item"><span class="meta-label">{escape(txt(labels, "meta_server_health"))}</span><span class="meta-value">{escape(server_health)}</span></div>
        <div class="meta-item"><span class="meta-label">{escape(txt(labels, "meta_generated_at"))}</span><span class="meta-value">{escape(generated_at)}</span></div>
      </div>
    </header>

    <section class="section">
      <div class="section-header"><h2>{escape(txt(labels, "section_overview"))}</h2></div>
      <div class="section-content"><div class="stats-grid">{cards_html}</div></div>
    </section>

    <section class="section">
      <div class="section-header"><h2>{escape(txt(labels, "section_quality_gate"))}</h2></div>
      <div class="section-content table-wrap">
        <table>
          <thead>
            <tr>
              <th>{escape(txt(labels, "col_metric"))}</th>
              <th>{escape(txt(labels, "col_status"))}</th>
              <th>{escape(txt(labels, "col_actual"))}</th>
              <th>{escape(txt(labels, "col_comparator"))}</th>
              <th>{escape(txt(labels, "col_threshold"))}</th>
            </tr>
          </thead>
          <tbody>{''.join(condition_rows)}</tbody>
        </table>
      </div>
    </section>

    <section class="section">
      <div class="section-header"><h2>{escape(txt(labels, "section_issue_summary"))}</h2></div>
      <div class="section-content">
        <div class="summary-row">
          <div class="summary-title">{escape(txt(labels, "summary_by_severity"))}</div>
          <div class="summary-chips">{severity_summary}</div>
        </div>
        <div class="summary-row">
          <div class="summary-title">{escape(txt(labels, "summary_by_type"))}</div>
          <div class="summary-chips">{type_summary}</div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="section-header"><h2>{escape(txt(labels, "section_issues_by_severity"))}</h2></div>
      <div class="section-content">{truncation_note}{grouped_by_severity_html}</div>
    </section>

    <section class="section">
      <div class="section-header"><h2>{escape(txt(labels, "section_issues_by_type"))}</h2></div>
      <div class="section-content">{grouped_by_type_html}</div>
    </section>

    <section class="section">
      <div class="section-header"><h2>{escape(txt(labels, "section_duplicates"))}</h2></div>
      <div class="section-content">
        <details class="issue-group" id="duplicate-files-root">
          <summary><span>{escape(txt(labels, "dup_group_title"))}</span><span class="summary-count">{duplicate_file_count}</span></summary>
          <div class="group-table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>{escape(txt(labels, "col_file"))}</th>
                  <th>{escape(txt(labels, "col_dup_lines"))}</th>
                </tr>
              </thead>
              <tbody>{''.join(duplicate_rows)}</tbody>
            </table>
          </div>
        </details>
      </div>
    </section>

    <div class="footer">{escape(txt(labels, "footer"))}</div>
  </main>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate an HTML report from SonarQube.")
    parser.add_argument("--host", default="http://localhost:9000", help="SonarQube host URL")
    parser.add_argument("--project", required=True, help="SonarQube project key")
    parser.add_argument("--token", required=True, help="SonarQube user token")
    parser.add_argument("--branch", default=None, help="Branch name (optional)")
    parser.add_argument("--output", default="sonar-report.html", help="Output HTML file path")
    parser.add_argument("--timeout", type=int, default=20, help="HTTP timeout in seconds")
    parser.add_argument(
        "--max-issues",
        type=int,
        default=0,
        help="Max issues to render (0 = all, useful for huge projects)",
    )
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Disable TLS cert verification (useful for self-signed local HTTPS)",
    )
    parser.add_argument(
        "--jp",
        action="store_true",
        help="Render report labels in Japanese",
    )
    args = parser.parse_args()
    labels = labels_for(args.jp)

    verify_ssl = not args.insecure
    if args.insecure:
        requests.packages.urllib3.disable_warnings()  # type: ignore[attr-defined]

    session = requests.Session()
    session.auth = (args.token, "")
    session.headers.update({"Accept": "application/json"})

    try:
        auth_data = api_get(
            session,
            args.host,
            "/api/authentication/validate",
            timeout=args.timeout,
            verify_ssl=verify_ssl,
        )
        if not auth_data or not auth_data.get("valid", False):
            print(txt(labels, "msg_auth_failed"), file=sys.stderr)
            return 2

        try:
            health_data = api_get(
                session,
                args.host,
                "/api/system/health",
                timeout=args.timeout,
                verify_ssl=verify_ssl,
            )
            server_health = (health_data or {}).get("health", "UNKNOWN")
        except Exception:
            server_health = "UNKNOWN"

        branch_name = args.branch or get_main_branch_name(
            session, args.host, args.project, args.timeout, verify_ssl
        )

        measures = get_measures(
            session, args.host, args.project, args.branch, args.timeout, verify_ssl
        )
        qg_data = get_quality_gate(
            session, args.host, args.project, args.branch, args.timeout, verify_ssl
        )
        latest = get_latest_analysis(
            session, args.host, args.project, args.branch, args.timeout, verify_ssl, labels
        )
        issues = get_all_unresolved_issues(
            session, args.host, args.project, args.branch, args.timeout, verify_ssl
        )
        duplicated_files = get_duplicated_files(
            session, args.host, args.project, args.branch, args.timeout, verify_ssl
        )

        qg_raw = (
            qg_data.get("projectStatus", {}).get("status")
            if qg_data
            else measures.get("alert_status")
        )

        generated_at = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_html = build_html(
            project_key=args.project,
            branch_name=branch_name,
            quality_gate_raw=qg_raw,
            quality_gate_data=qg_data,
            measures=measures,
            latest_analysis=latest,
            issues=issues,
            duplicated_files=duplicated_files,
            server_health=server_health,
            generated_at=generated_at,
            max_issues=args.max_issues,
            use_jp=args.jp,
        )

        out_path = Path(args.output).resolve()
        out_path.write_text(report_html, encoding="utf-8")
        print(txt(labels, "msg_report_generated").format(path=out_path))
        return 0

    except RequestException as ex:
        print(txt(labels, "msg_http_error").format(error=ex), file=sys.stderr)
        return 1
    except Exception as ex:
        print(txt(labels, "msg_unexpected_error").format(error=ex), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
