-- UPDATE notices
-- SET start_hour = COALESCE(start_hour, '00:00'),
--     end_hour = COALESCE(end_hour, '00:00'),
--     money = COALESCE(money, '')
-- WHERE start_hour IS NULL OR end_hour IS NULL OR money IS NULL;
