DELETE FROM user_role_permissions
WHERE user_id IN (4, 5, 6, 7, 8, 9, 10, 11, 12);

INSERT INTO user_role_permissions
  (user_id, resource, permission_level, created_at, updated_at)
VALUES
-- gotou: admin = 3
(4, '101', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '102', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '103', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '201', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '202', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '203', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '204', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- taichi/wada/takamura: user = 2
(5, '101', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '102', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '103', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '201', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '202', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '203', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '204', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, '101', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '102', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '103', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '201', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '202', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '203', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '204', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(7, '101', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '102', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '103', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '201', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '202', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '203', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '204', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- viewer = 1
(8, '101', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '102', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '103', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '201', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '202', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '203', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '204', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(9, '101', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '102', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '103', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '201', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '202', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '203', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '204', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(10, '101', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '102', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '103', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '201', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '202', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '203', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '204', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(11, '101', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '102', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '103', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '201', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '202', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '203', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '204', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(12, '101', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '102', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '103', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '201', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '202', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '203', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '204', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);