CREATE TABLE IF NOT EXISTS practiceMenuHeader (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  remarks TEXT,
  updater TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS practiceMenuDetail (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  headerId INTEGER NOT NULL,
  category TEXT,
  menuName TEXT NOT NULL,
  menuTime INTEGER,
  timeWhite TEXT,
  startTime TEXT,
  endTime TEXT,
  sortNo INTEGER NOT NULL,
  updater TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (headerId)
    REFERENCES practiceMenuHeader(id)
    ON DELETE CASCADE
);