apiVersion: 1

deleteDatasources:
  - name: InfluxDB-OTel
    orgId: 1

datasources:
  - name: InfluxDB-OTel
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB}
    user: ${INFLUXDB_ADMIN_USER}
    secureJsonData:
      password: ${INFLUXDB_ADMIN_PASSWORD}
    isDefault: true
    editable: false
    jsonData:
      httpMode: POST
      timeInterval: 30s
