INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-01', '1', '全権承認', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-02', '2', '全権更新', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-03', '3', '全権参照', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-04', '4', '全権なし', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-05', '11', '申請中（ユニークCD一覧のみ）', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-06', '5', '削除', '1', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-07', '5', '承認済（表示）', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-08', '6', '削除', '1', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-09', '6', '承認済削除（検索可能）', '1', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-10', '7', '承認済（表示）', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-11', '7', '申請中', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-12', '8', '承認済（表示）', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-13', '8', '申請取下', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-14', '9', '承認済（表示）', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-15', '9', '差戻', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-16', '10', '削除', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');
INSERT INTO master_role (id, unique_id, role_name, deleted_flag, reason_for_deletion, creator_user_id, created_date_and_time, updater_user_id, updated_date_and_time) VALUES ('RI-20250620-17', '10', '削除申請中', '0', NULL, 'sys-b@email.com', '2025/06/23', 'sys-b@email.com', '2025/06/23');

