INSERT INTO error_codes (code, locale, message) VALUES
('E400', 'ja', 'リクエストが不正です'),
('E400', 'en', 'Invalid request'),
('E401', 'ja', '認証に失敗しました'),
('E401', 'en', 'Authentication failed'),
('E403', 'ja', '権限がありません'),
('E403', 'en', 'Access denied'),
('E404', 'ja', '対象が見つかりません'),
('E404', 'en', 'Resource not found'),
('E500', 'ja', 'サーバー内部エラー'),
('E500', 'en', 'Internal server error'),
('E001', 'ja', '予期しないエラーが発生しました'),
('E001', 'en', 'Unexpected error'),
('E003', 'ja', '既に登録されています'),
('E003', 'en', 'Already registered'),
('E008', 'ja', '必須データが見つかりません'),
('E008', 'en', 'Essential data not found'),
('E009', 'ja', 'データ競合が発生しました'),
('E009', 'en', 'Conflict detected'),
('E020', 'ja', '入力日付が不正です'),
('E020', 'en', 'Invalid input date'),
('E090', 'ja', '実績数量が上限を超えています'),
('E090', 'en', 'Actual amount exceeds capacity'),
('E097', 'ja', '処理中のデータがあるため登録できません'),
('E097', 'en', 'Cannot register due to in-progress data'),
('E098', 'ja', '開始日より後の開始日データが存在します'),
('E098', 'en', 'Later start date data exists'),
('E1010', 'ja', '対象データが見つかりません'),
('E1010', 'en', 'Target data not found'),
('E1012', 'ja', 'ファイル処理に失敗しました'),
('E1012', 'en', 'File processing failed'),
('E104', 'ja', '関連マスタが見つかりません'),
('E104', 'en', 'Related master not found'),
('E105', 'ja', 'シートが見つかりません'),
('E105', 'en', 'Sheet not found'),
('E121', 'ja', '更新できないステータスです'),
('E121', 'en', 'Update not allowed for current status'),
('E190', 'ja', '帳票データ取得に失敗しました'),
('E190', 'en', 'Failed to fetch report data')
;
