package com.example.servercommon.utils;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import com.example.servercommon.message.BackendMessageCatalog;
import com.github.f4b6a3.ulid.UlidCreator;
/**
 * 採番処理が必要な場合に使用するクラス
 */
public class PrimaryKeyGenerator {
    public static <T> T generateIfNeeded(Class<T> type) {
        if (type == String.class) {
            return type.cast(UlidCreator.getUlid().toString());
        }

        // int,long,Long,Integer の場合,DBのautogenerated を使うので採番処理が不要
        if (type == Long.class || type == Integer.class || type == int.class || type == long.class) {
            return null;
        }

        throw new IllegalArgumentException(BackendMessageCatalog.format(
                BackendMessageCatalog.EX_UNSUPPORTED_KEY_TYPE, type.getName()));
    }

}
