import { Hono } from "hono";
import { getDb, type AppVariables, type Bindings } from "../env";
import { createPracticeMovie, deletePracticeMovie, findAllPracticeMovies, findPracticeMovieById, updatePracticeMovie } from "../repositories/practiceMoviesRepository";
import type { PracticeMovieCreateInput } from "../types/practiceMovies";

export const practiceMoviesRoutes = new Hono<{ Bindings: Bindings; Variables: AppVariables }>();
const parseId = (value: string) => { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : null; };
const authorOf = (c: any) => c.get("auth")?.user?.displayName?.trim() || c.get("auth")?.user?.userId?.trim();
const inputOf = async (c: any) => { const body = await c.req.json().catch(() => null) as Partial<PracticeMovieCreateInput> | null; return { title: typeof body?.title === "string" ? body.title.trim() : "", url: typeof body?.url === "string" ? body.url.trim() : "", label: typeof body?.label === "string" ? body.label.trim() : "", note: typeof body?.note === "string" ? body.note.trim() || null : null }; };

practiceMoviesRoutes.get("/practicemovies", async (c) => c.json(await findAllPracticeMovies(getDb(c.env), { title: c.req.query("title"), label: c.req.query("label") })));
practiceMoviesRoutes.get("/practicemovies/mine", async (c) => { const auth = c.get("auth"); const author = authorOf(c); return !auth?.authenticated || !author ? c.json({ error: { code: "UNAUTHORIZED", message: "Authentication required" }, requestId: c.get("requestId") }, 401) : c.json(await findAllPracticeMovies(getDb(c.env), { author })); });
practiceMoviesRoutes.get("/practicemovies/:id", async (c) => { const id = parseId(c.req.param("id")); if (id === null) return c.json({ error: { code: "BAD_REQUEST", message: "Invalid practice movie id" } }, 400); const item = await findPracticeMovieById(getDb(c.env), id); return item ? c.json(item) : c.json({ error: { code: "NOT_FOUND", message: "Practice movie not found" } }, 404); });
practiceMoviesRoutes.post("/practicemovies", async (c) => { const auth = c.get("auth"); const author = authorOf(c); if (!auth?.authenticated || !author) return c.json({ error: { code: "UNAUTHORIZED", message: "Authentication required" } }, 401); if ((auth.roleLevel ?? 0) < 2) return c.json({ error: { code: "FORBIDDEN", message: "Insufficient permission" } }, 403); const input = await inputOf(c); if (!input.title || !input.url || !input.label) return c.json({ error: { code: "BAD_REQUEST", message: "title, url and label are required" } }, 400); const item = await createPracticeMovie(getDb(c.env), { ...input, author }); return item ? c.json(item, 201) : c.json({ error: { code: "INTERNAL_SERVER_ERROR", message: "Failed to create practice movie" } }, 500); });
practiceMoviesRoutes.put("/practicemovies/:id", async (c) => { const auth = c.get("auth"); const author = authorOf(c); const id = parseId(c.req.param("id")); if (!auth?.authenticated || !author) return c.json({ error: { code: "UNAUTHORIZED", message: "Authentication required" } }, 401); if ((auth.roleLevel ?? 0) < 2) return c.json({ error: { code: "FORBIDDEN", message: "Insufficient permission" } }, 403); if (id === null) return c.json({ error: { code: "BAD_REQUEST", message: "Invalid practice movie id" } }, 400); const current = await findPracticeMovieById(getDb(c.env), id); if (!current) return c.json({ error: { code: "NOT_FOUND", message: "Practice movie not found" } }, 404); if (current.author !== author) return c.json({ error: { code: "FORBIDDEN", message: "Only the author can update this practice movie" } }, 403); const input = await inputOf(c); if (!input.title || !input.url || !input.label) return c.json({ error: { code: "BAD_REQUEST", message: "title, url and label are required" } }, 400); return c.json(await updatePracticeMovie(getDb(c.env), id, input)); });
practiceMoviesRoutes.delete("/practicemovies/:id", async (c) => { const auth = c.get("auth"); const author = authorOf(c); const id = parseId(c.req.param("id")); if (!auth?.authenticated || !author) return c.json({ error: { code: "UNAUTHORIZED", message: "Authentication required" } }, 401); if ((auth.roleLevel ?? 0) < 2) return c.json({ error: { code: "FORBIDDEN", message: "Insufficient permission" } }, 403); if (id === null) return c.json({ error: { code: "BAD_REQUEST", message: "Invalid practice movie id" } }, 400); const current = await findPracticeMovieById(getDb(c.env), id); if (!current) return c.json({ error: { code: "NOT_FOUND", message: "Practice movie not found" } }, 404); if (current.author !== author) return c.json({ error: { code: "FORBIDDEN", message: "Only the author can delete this practice movie" } }, 403); await deletePracticeMovie(getDb(c.env), id); return c.json({ success: true }); });
