INSERT INTO error_codes (code, locale, message) VALUES
('E400', 'ja', 'リクエスト内容が不正です'),
('E400', 'en', 'Invalid request'),
('E401', 'ja', '認証に失敗しました'),
('E401', 'en', 'Authentication failed'),
('E403', 'ja', '権限がありません'),
('E403', 'en', 'Access denied'),
('E404', 'ja', '対象が見つかりませんでした'),
('E404', 'en', 'Resource not found'),
('E409', 'ja', 'データの整合性エラーが発生しました'),
('E409', 'en', 'Conflict detected'),
('E422', 'ja', '入力内容に誤りがあります'),
('E422', 'en', 'Unprocessable input'),
('E500', 'ja', 'サーバー内部でエラーが発生しました'),
('E500', 'en', 'Internal server error');
('E1001', 'ja', 'ユーザーが存在しません'),
('E1001', 'en', 'User not found'),
('E1002', 'ja', 'パスワードが正しくありません'),
('E1002', 'en', 'Incorrect password'),
('E1003', 'ja', 'アカウントが無効です'),
('E1003', 'en', 'Account is inactive'),
('E1004', 'ja', 'ユーザーはすでに存在します'),
('E1004', 'en', 'User already exists'),
('E1005', 'ja', 'この操作を行う権限がありません'),
('E1005', 'en', 'You do not have permission'),
('E1006', 'ja', 'ログインに失敗しました'),
('E1006', 'en', 'Login failed'),
('E1007', 'ja', '必須項目が入力されていません'),
('E1007', 'en', 'Required fields are missing'),
('E1008', 'ja', '入力形式が正しくありません'),
('E1008', 'en', 'Invalid input format'),
('E1009', 'ja', 'セッションが切れています。再度ログインしてください'),
('E1009', 'en', 'Session expired, please login again'),
('E1010', 'ja', '対象データが見つかりませんでした'),
('E1010', 'en', 'Target data not found'),
('E1011', 'ja', 'データベースエラーが発生しました。'),
('E1011', 'en', 'A database error occurred.'),
('E015', 'ja', '選択した日付は業務締されているため選択できません。'),
('E015', 'en', 'BusinessClosure is closed for selected date'),
('E003', 'ja', '登録済のため使用できない{0}CDです。'),
('E003', 'en', 'already registered {0}CD.'),
('E020', 'ja', '{0}は{1}以降の日付を選択してください。'),
('E020', 'en', 'For {0}, please select a date after {1}.'),
('E097', 'ja', '申請中のデータがあるため、登録できません。'),
('E097', 'en', 'You cannot register because there is data in progress.'),
('E098', 'ja', '選択されている適用開始日より未来の適用開始日のデータが存在するため、登録できません。'),
('E098', 'en', 'Registration is not possible as there is data with a later start date than the selected start date.'),
('E103', 'ja', '取込ファイルに不正なデータが含まれているため、処理を中止しました。'),
('E103', 'en', 'there was error while processing file.'),
('E104', 'ja', 'マスタに存在しない値が{0}に設定されているため、登録できません。'),
('E104', 'en', 'Given Value{0} is not found in related master table'),
('E105', 'ja', '{0}シートが存在しないため、登録できません。'),
('E105', 'en', 'There is no {0}sheet name'),
('E1012', 'en', 'File Processing failed'),
('E1012', 'ja', 'ファイルの読み込み処理が失敗しました。'),
('E121', 'en', 'Current status{0} is not for Update Process,Cannot update'),
('E121', 'ja', '処理区分{0} が行えないステータスのため、{0}できません。'),
('E013', 'ja', 'マスタに存在しない値が {0} に設定されているため、登録できません。')
('E1013', 'ja', '不正なジョブ名。'),
('E1013', 'en', 'Invalid Job Name'),
('E4031', 'ja', 'アクセスが拒否されました。権限がありません。'),
('E4031', 'en', 'Access has been denied. You lack the necessary permissions.'),
('E4002', 'ja', 'パラメータが不正です。'),
('E4002', 'en', 'Invalid Parameter.'),
('E1011', 'ja', 'データベースエラーが発生しました。'),
('E1011', 'en', 'DataBase Error Occured.'),
('E5001', 'ja', '予期せぬエラーが発生しました。'),
('E5001', 'en', 'An unexpected error occured.'),
('E5201', 'ja', 'ストレージエラー発生。'),
('E5201', 'en', 'Storage error occurred.'),
('E5101', 'ja', '帳票生成中にエラーが発生しました。'),
('E5101', 'en', 'An error occurred during report generation.'),
('E6001', 'ja', 'ファイルインポート中にエラーが発生'),
('E6001', 'en', 'error occured while importing file')
;
